### ISSUE TITLE
Utilize Quickfix window in Neovim

### ISSUE THREAD

**Issue by shivangp76** [Myriad-Dreamin/tinymist#1001]
**Motivation**

This would allow Typst compiler errors to be easily visible. Currently, LSP integration allows most errors to be seen on their respective lines, but something like the following is not visible. The goal is to have this visible in the Quickfix window.

```typst
#import "@preview/physica:0.9.3": *
$ dv(x) $
```
In this example, `dv(x)` should be `dv(,x)`. The full compiler error is below. This does not get shown in the buffer, so there is no way to know the document failed to compile and where the error is without manually running `typst compile` in another terminal.
<img width="598" alt="image" src="https://github.com/user-attachments/assets/5d63d711-0689-4230-8e84-e305674d02f0" />

**Description**

Integrate with [Quickfix](https://neovim.io/doc/user/quickfix.html#quickfix) in Neovim

**Examples/Questions**

Below is how this feature looks in Vimtex, for inspiration:
<img width="542" alt="image" src="https://github.com/user-attachments/assets/ee50d7cb-b930-4112-88b0-58db6a610080" />

**Comment by Myriad-Dreamin** [comment]
To be clear, is it the problem of tinymist or QuickFix plugin? This question is raised because tinymist should have shown the diagnostic message on some LSP clients (VS Code).

![image](https://github.com/user-attachments/assets/8ca640ae-ca93-44d9-b459-d1115bbcd7d1)

**Comment by Eric-Song-Nop** [comment]
This error is definitely shown in the lsp error, thus could be found if you setup quickfix or trouble properly. You cannot see this error might because this error is not considered to appear in the current file, but in the `physica` module

**Comment by Eric-Song-Nop** [comment]
In other word, Tinymist cannot tell that this error is in current buffer for now.

**Comment by shivangp76** [comment]
@Eric-Song-Nop Could you please share your Neovim setup in the screenshot that allowed you to see the error in the physica module?

**Comment by Eric-Song-Nop** [comment]
I am using the [trouble.nvim](https://github.com/folke/trouble.nvim) plugin

**Comment by shivangp76** [comment]
Thank you! Fixing my setup did the trick.
