### ISSUE TITLE
Expose `typstyle` as a subcommand for standalone usage?

### ISSUE THREAD

**Issue by rami3l** [Myriad-Dreamin/tinymist#1007]
Thanks a lot for making this awesome project! I've been daily-driving `tinymist` on Neovim for months now.

**Motivation**

I've noticed that `tinymist` is already embedding `typstyle`:

https://github.com/Myriad-Dreamin/tinymist/blob/3cdd9f25082c1ad62e9160bdd9b68cc692e7d186/Cargo.toml#L115

... wouldn't it be beneficial if `tinymist` can be used as a standalone formatter, so that in config scenarios such as that of [`conform.nvim`](https://github.com/stevearc/conform.nvim?tab=readme-ov-file#formatters), it will no longer be required to install `typstyle` in addition to `tinymist`?

**Description**

Expose the formatting feature as a subcommand (such as `tinymist fmt`) that can be used as a drop-in replacement for `typstyle`, in a way similar to the previous integration of [`typst-preview`](https://github.com/Enter-tainer/typst-preview).

**Comment by Enter-tainer** [comment]
hi, i would say the simplest solution in this case is to install typstyle on your machine.

But it does has problems: you might use different versions of typstyle and tinymist. so format result can be unstable.

**Comment by Enter-tainer** [comment]
> so that in config scenarios such as that of conform.nvim

I'm not sure about this part. iiuc tinymist as a language server can already format source files in your editor.

**Comment by Parsifa1** [comment]
https://github.com/stevearc/conform.nvim#setupopts
![image](https://github.com/user-attachments/assets/1318db8a-85b3-4fe1-b1dd-035c37056e71)
it seems that, conform.nvim will get lsp-format fallback for free, if only your tinymist is on boarding :)

**Comment by Myriad-Dreamin** [comment]
Thank you for loving it!

There are two main reasons that we do not expose a CLI for typstyle:
- There are two formatters in tinymist, and we must make common CLI functions for these formatters. We might also add few good alterantives in future (I expect not though).
- typstyle-cli has richer formatter actions, e.g. `fmt --recursive` which recursively format files in a directory, and we'll ultimately have to keep syncing these CLI for people if we start to provide a `fmt` command.

All of that conclude to a single word "extra unnecessary effort". So I think it is acceptable to add a `fmt` command if someone would like to PR to add and maintain it.

PS: I have some wilder thinking, that is to add a harness subcommand `tinymist typstyle ..` that completely install typstyle's commands, thought this looks a bit ugly. I was using some similar harness command that `llvm-cov` expose a `gcov` subcommand to simulate behavior of `gcov`.

**Comment by Myriad-Dreamin** [comment]
> iiuc tinymist as a language server can already format source files in your editor.

True. The most correct way to call formatter in tinymist is undoubtly using the editor commands. I believe neovim as a powerful editor must provide them.

**Comment by rami3l** [comment]
Thanks everyone for the quick response!

@Enter-tainer Reading the thread, my conclusion would be that I was probably not asking the right question for my specific problem.
Thus, you may close this issue if you like.

@Parsifa1's Thanks for your suggestion of using `fallback`!
I am aware of this option and have manually setting it to `fallback` for `typst` without success.
Similarly, issuing `:lua vim.lsp.buf.format()` gives `ERROR: [LSP] Format request failed, no matching language servers.`
Comparing the server capabilities returned by `tinymist` and `rust-analyzer` (the latter works perfectly with both `conform` fallback and `:lua vim.lsp.buf.format()`), I can see `documentFormattingProvider` is missing, although I'm still new to this topic and cannot say for sure whether that is the right direction.

If it helps, my current `tinymist` setup is the following:

```lua
---@type lspconfig.options.tinymist
---@diagnostic disable: missing-fields
return {
  -- HACK: Works around https://github.com/Myriad-Dreamin/tinymist/issues/638.
  -- See https://github.com/Myriad-Dreamin/tinymist/issues/638#issuecomment-2395941103 for more info.
  offset_encoding = "utf-8",
  settings = {
    tinymist = {
      formatterMode = "typstyle",
    },
  },
}
```

**Comment by Eric-Song-Nop** [comment]
> However, my previous question was exactly why I didn't manage to get vim.lsp.buf.format() working, otherwise conform would have picked it up.
I have no idea, it works smoothly on my side. I only get `ERROR: [LSP] Format request failed, no matching language servers.` when formattermode is set to disable, and this should be the ideal behavior.

**Comment by Enter-tainer** [comment]
Hi, can we close this issue now? I believe the X problem has already been solved
