### ISSUE TITLE
Prose Wrapping

### ISSUE THREAD

**Issue by mahyarmirrashed** [Myriad-Dreamin/tinymist#1016]
**Motivation**

I'm rewriting my resume with `typst` (first time) and frequently have to write long lines. 

**Description**

I like Prettier's prose-wrapping feature for my Markdown source files. After 80/88 lines, it wraps the next word to the following line. It doesn't affect the output since you need two spaces in Markdown to signify the start of the next paragraph. Something similar with Typst, if within the realm of the spec, would be great.

**Examples/Questions**

I'm wondering how this would work for long headers, long item in lists, or elsewhere. I can link to the Prettier documentation on the option, and maybe it can be engineered here: https://prettier.io/docs/en/options.html#Prose-Wrap

**Comment by Eric-Song-Nop** [comment]
Typstyle doesn't format content for you but only format code in Typst. Typstfmt does respect the line width limit, which is by default 120 set by tinymist, thus you can set [formattermode](https://github.com/Myriad-Dreamin/tinymist/blob/main/editors/neovim/Configuration.md#formattermode) to typstfmt and take the risk of breaking your content.

**Comment by mahyarmirrashed** [comment]
Thanks! What are your thoughts on adding this feature?
One person on Discord brought up a good point about mess `git diff` if it is enabled. But it could just be an opt-in feature like Prettier.

**Comment by Myriad-Dreamin** [comment]
Hey, not sure whether it is https://github.com/Enter-tainer/typstyle/issues/104, whatever we should move discussion about formatting to the active upstream, typstyle.

**Comment by mahyarmirrashed** [comment]
Ok, I'll close this thread then.
