### ISSUE TITLE
How to make `tinymist`'s LSP-based formatting play well with Neovim via `conform.nvim`?

### ISSUE THREAD

**Issue by rami3l** [Myriad-Dreamin/tinymist#1018]
**Describe the bug**
Coming from https://github.com/Myriad-Dreamin/tinymist/issues/1007#issuecomment-2544656738, it seems like `conform.nvim` supports formatting Typst code with LSP-based formatting, but I didn't manage to set it up properly for some reason.

I've noted that:
1. `conform.nvim` failed to perform "format on save" with the setup described below.
2. `tinymist` shows up correctly in `:LspInfo`.
3. `formatterMode` has been set to `"typstyle"`, but `:lua vim.lsp.buf.format()` still gives `ERROR: [LSP] Format request failed, no matching language servers.`
4. Comparing the server capabilities returned by `tinymist` and `rust-analyzer` (the latter works perfectly with both `conform` fallback and `:lua vim.lsp.buf.format()`), I can see [`documentFormattingProvider`](https://github.com/rust-lang/rust-analyzer/blob/27e824fad4cb40f9e475757871e7d259d73f20da/crates/rust-analyzer/src/lsp/capabilities.rs#L74) is missing.

My speculation is that if somehow `:lua vim.lsp.buf.format()` can be made to work with `tinymist`, `conform.nvim` would then be able to rely on that for formatting.

**Package/Software version:**

Neovim version:
```plain
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1734355927
```

tinymist version:
```plain
tinymist 
Build Timestamp:     2024-12-16T17:48:31.427672000Z
Build Git Describe:  v0.12.12
Commit SHA:          d3269f521a3b537c346ee97b9c547c94160d8fea
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: aarch64-apple-darwin
Typst Version:       0.12.0
Typst Source:        git+https://github.com/Myriad-Dreamin/typst.git?tag=tinymis
t-v0.12.0#58426a90a7ef721738a01be09793d33e55eb75a9
```

**Additional context**

The configs that I'm using for the test are the following:

```lua
---@type lspconfig.options.tinymist
---@diagnostic disable: missing-fields
return {
  -- HACK: Works around https://github.com/Myriad-Dreamin/tinymist/issues/638.
  -- See https://github.com/Myriad-Dreamin/tinymist/issues/638#issuecomment-2395941103 for more info.
  offset_encoding = "utf-8",
  settings = {
    tinymist = {
      formatterMode = "typstyle",
    },
  },
}
```

```lua
  {
    "stevearc/conform.nvim",
    optional = true,
    opts = {
      formatters_by_ft = {
        typst = { "typstyle", lsp_format = "prefer" },
      },
    },
  },
```

**Comment by rami3l** [comment]
I've caught the error log, it looks like `formatterMode` haven't been passed correctly:

> [ERROR][2024-12-18 14:07:58] .../vim/lsp/rpc.lua:770	"rpc"	"redacted/mason/bin/tinymist"	"stderr"	'[2024-12-18T06:07:58Z INFO  tinymist] tinymist version information: [["Build Timestamp", "2024-12-16T17:48:31.427672000Z"], ["Build Git Describe", "v0.12.12"], ["Commit SHA", "d3269f521a3b537c346ee97b9c547c94160d8fea"], ["Commit Date", "None"], ["Commit Branch", "None"], ["Cargo Target Triple", "aarch64-apple-darwin"], ["Typst Version", "0.12.0"], ["Typst Source", "git+https://github.com/Myriad-Dreamin/typst.git?tag=tinymist-v0.12.0#58426a90a7ef721738a01be09793d33e55eb75a9"]]\n[2024-12-18T06:07:58Z INFO  tinymist] starting Language server: LspArgs {\n        mirror: MirrorArgs {\n            mirror: "",\n            replay: "",\n        },\n        font: CompileFontArgs {\n            font_paths: [],\n            ignore_system_fonts: false,\n        },\n    }\n[2024-12-18T06:07:58Z INFO  sync_lsp] handling initialize - (1) at Instant { tv_sec: 79811, tv_nsec: 166547750 }\n[2024-12-18T06:07:58Z INFO  tinymist::init] color theme: None\n[2024-12-18T06:07:58Z INFO  tinymist::server] LanguageState: initialized with config Config { const_config: ConstConfig { position_encoding: Utf16, cfg_change_registration: true, notify_will_rename_files: true, tokens_dynamic_registration: false, tokens_overlapping_token_support: true, tokens_multiline_token_support: false, doc_line_folding_only: true, doc_fmt_dynamic_registration: true }, compile: CompileConfig { output_path: PathPattern(""), export_pdf: Never, font_opts: CompileFontArgs { font_paths: [], ignore_system_fonts: false }, system_fonts: None, font_paths: [], fonts: OnceCell(Uninit), notify_status: false, periscope_args: None, typst_extra_args: Some(CompileExtraOpts { root_dir: None, entry: None, inputs: {}, font: CompileFontArgs { font_paths: [], ignore_system_fonts: false }, package: CompilePackageArgs { package_path: None, package_cache_path: None }, creation_timestamp: None, cert: None }), color_theme: None, has_default_entry_path: false, lsp_inputs: {"x-preview": "{\\"version\\":1,\\"theme\\":\\"\\"}"}, entry_resolver: EntryResolver { root_path: None, roots: ["redacted"], entry: None } }, semantic_tokens: Enable, **_formatter_mode: Disable_**, formatter_print_width: None, support_html_in_markdown: false, completion: CompletionFeat { trigger_on_snippet_placeholders: false, trigger_suggest: false, trigger_parameter_hints: false, trigger_suggest_and_parameter_hints: false, postfix: None, postfix_ufcs: None, postfix_ufcs_left: None, postfix_ufcs_right: None, postfix_snippets: None } }\n[2024-12-18T06:07:58Z INFO  tinymist::actor] TypstActor: creating server for primary, entry: EntryState { rooted: true, root: Some("redacted"), main: None }, inputs: {"x-preview": "{\\"version\\":1,\\"theme\\":\\"\\"}"}\n[2024-12-18T06:07:58Z INFO  tinymist::init] creating SharedFontResolver with CompileFontArgs { font_paths: [], ignore_system_fonts: false }\n[2024-12-18T06:07:58Z INFO  sync_lsp] handled  initialize - (1) in 412.29µs\n'

**Comment by Myriad-Dreamin** [comment]
Does other configuration work e.g. `exportPdf`?

**Comment by Eric-Song-Nop** [comment]
You are setting it wrong!

```lua
  settings = {
    tinymist = {
      formatterMode = "typstyle",
    },
  },
```
is incorrect, use 

```lua
  settings = {
      formatterMode = "typstyle",
  },
``` 
instead, check this link for how to config tinymist with neovim lsp: https://github.com/Myriad-Dreamin/tinymist/tree/e116b0b6451bbac880a6196cc7a6a4e0ddb44aa6/editors/neovim#configuring-language-server

**Comment by Eric-Song-Nop** [comment]
Btw, it is not related to conform, you can test with calling `:lua vim.lsp.buf.format()` directly. For conform, I recommend set lsp to fallback or not use it at all, tinymist format has all the optimizations from conform.

**Comment by rami3l** [comment]
> You are setting it wrong!
> 
> ```lua
>   settings = {
>     tinymist = {
>       formatterMode = "typstyle",
>     },
>   },
> ```
> 
> is incorrect, use
> 
> ```lua
>   settings = {
>       formatterMode = "typstyle",
>   },
> ```
> 
> instead, check this link for how to config tinymist with neovim lsp: https://github.com/Myriad-Dreamin/tinymist/tree/e116b0b6451bbac880a6196cc7a6a4e0ddb44aa6/editors/neovim#configuring-language-server

@Eric-Song-Nop Thanks a lot for your diagnosis, you saved my day!

However, it seems to me that something has gone wrong with the `@type lspconfig.options.tinymist` schema since the "correct" configuration you've posted does not correspond to that schema. My guess would be that the corresponding gluing code in Neovim somehow has become incoherent (either the schema or the implementation is wrong). Anyway, I'm closing this issue first unless I'm convinced that something in `tinymist` needs to be adjusted, and I'll report this issue to Neovim's side and see how it goes.

Thanks again for your help, and have a nice day🙏
