### ISSUE TITLE
Bubble up package errors into files where they are imported

### ISSUE THREAD

**Issue by Andrew15-5** [Myriad-Dreamin/tinymist#1030]
**Motivation**

tinymist becomes literally useless when it comes to error reporting if the error occurs in some imported package, but that exact file where the error occurs is not opened (you would almost never every do that anyway). This forces me to reserve to opening a shell and compiling the document manually and looking at why it has stopped compiling.

**Description**

I want to see the package error in all relevant files, which can be configured (where to show them).

**Examples/Questions**

- If you `import pkg` in `main.typ` and after doing something, the error in `pkg/a/b/c.typ` should bubble up in `main.typ` where the `pkg` is imported.
- If you include `chapter1.typ` in `main.typ`, and `pkg` is imported in `chapter1.typ`, then the error should be seen in both `main.typ` (where the `chapter1.typ` is included) and `chapter1.typ` (where the `pkg` is imported`).
- One thing is that the error either have to be prefixed with `error from xxx: ` or just copied verbatim, though the first one feels much more user-friendly.

**Comment by Myriad-Dreamin** [comment]
It should be the same issue as #1001.
