### ISSUE TITLE
vscode snippets in math mode

### ISSUE THREAD

**Issue by gotycbc** [Myriad-Dreamin/tinymist#1053]
I use vscode snippets to type many unicode math symbols. For example, for `ℝ` I don't use typst's `RR` but use `R` to trigger suggestion to get `ℝ`. This is for readability. 

snippet setting:

	"ℝ":{
		"prefix": "R",
		"body": "ℝ",
		"description": "real"
	},

In tinymist `0.12.10`, this work, and now I downgrade to it

In `0.12.12`, type `R` after (or before) `$`, in suggestion list I cannot find `ℝ` but find `$R`. Add space between `$`, `ℝ` appear, but adding space between `$` make it not inline math

**Comment by Myriad-Dreamin** [comment]
https://github.com/Myriad-Dreamin/tinymist?tab=readme-ov-file#installing-regularnightly-prebuilds-from-github
