### ISSUE TITLE
ctrl+k,v doesn't open preview

### ISSUE THREAD

**Issue by NoamDev** [Myriad-Dreamin/tinymist#1067]
**Describe the bug**
When I press ctrl+k,v nothing happens, on the left bottom, I see "ctrl+k,v is not a command"
**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.96.2 (user setup)
Commit: fabdb6a30b49f79a7aba0f2ad9df9b399473380f
Date: 2024-12-19T10:22:47.216Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631
```

tinymist extension version: `0.12.14`.

**Comment by Myriad-Dreamin** [comment]
It works on my end. Perhaps you didn't focus any typst document to preview.

**Comment by NoamDev** [comment]
It turns out to have been my misunderstanding. I expected it to be "ctrl+k, ctrl+v" but instead it ws "ctrl+k, v"
