### ISSUE TITLE
support install by home-brew on macos

### ISSUE THREAD

**Issue by zanglg** [Myriad-Dreamin/tinymist#152]
As mentioned in the title, this way, one can utilize the system's package management capabilities for installation and updates.

**Comment by Myriad-Dreamin** [comment]
What can I help you? I don't have a macOS tho.

**Comment by zanglg** [comment]
Home-brew is a package manager on macOS, like mason-registry.dev but for macOS, not just for nvim. I don't have any relevant experience.

**Comment by Myriad-Dreamin** [comment]
I find it https://docs.brew.sh/Installation#linux-or-windows-10-subsystem-for-linux. I will try it when I schedule a time.

**Comment by zanglg** [comment]
also, in want to support scoop on windows, aur on archlinux, 😄

**Comment by Myriad-Dreamin** [comment]
> also, in want to support scoop on windows, aur on archlinux, 😄

You the kid asking for too many sweets 😈, /s.

Okay, I will also look at that software registries.

**Comment by Enter-tainer** [comment]
> also, in want to support scoop on windows, aur on archlinux, 😄

I would encourage you working on this if this can benefit your workflow.

**Comment by Myriad-Dreamin** [comment]
I'll close it as not planning. This does not mean that I'm not concerned but it is not a really issue.

Once tinymist are registered to those registries by someone or me, they will be listed in the [installation section in README](https://github.com/Myriad-Dreamin/tinymist?tab=readme-ov-file#installation).
