### ISSUE TITLE
vscode color bug

### ISSUE THREAD

**Issue by Wongboo** [Myriad-Dreamin/tinymist#194]
```
vscode tinymist typst 0.11.4
```
triggers the bug, the coloring should be consistent within three brackets. After changing math equation from `$ x^"#" = "argmin"_(A x=b) ||x||_(cal(l)_2) $` to `$ x_1 $` , problem disappears.
<img width="550" alt="截屏2024-04-18 10 05 42" src="https://github.com/Myriad-Dreamin/tinymist/assets/44860323/a9dd065e-60ed-4ee2-8f91-12f3efe26bb4">
the typst code
```
#import "@preview/touying:0.4.0": *

#let s = themes.simple.register()
#let (init, slides) = utils.methods(s)
#show: init

#let (slide, empty-slide) = utils.slides(s)
#show: slides

= Title

== First Slide

#slide[
  Hello, Touying! Hello, Typst!
	$ x^"#" = "argmin"_(A x=b) ||x||_(cal(l)_2) $
]

#slide[
  Hello, Touying! Hello, Typst!
	$ x^"#" = "argmin"_(A x=b) ||x||_(cal(l)_2) $
]

#slide[
  Hello, Touying! Hello, Typst!
	$ x^"#" = "argmin"_(A x=b) ||x||_(cal(l)_2) $
]
```

**Comment by Wongboo** [comment]
change to
`
  $ x^hash = "argmin"_(A x=b) ||x||_(cal(l)_2) $
`
or
`
  $ x^"'" = "argmin"_(A x=b) ||x||_(cal(l)_2) $
`
problem also disappears, the problem rises from `"#"`!

**Comment by Myriad-Dreamin** [comment]
Thank you for reporting! Since we have introduced syntax highlighting, as what Rust/C++/... do, there may be some bad syntax rendering. I will fix it soonly.
