### ISSUE TITLE
[Feature Request] Export specific pages as images with custom PPI

### ISSUE THREAD

**Issue by ParaN3xus** [Myriad-Dreamin/tinymist#197]
**Describe the feature**
Export specific pages as images with custom PPI.

**Details** (still open for discussion)
I propose adding two new options to the "Export as" menu: `"PNG (Specific Pages)"` and `"SVG (Specific Pages)"`. 

When one of these options is selected, the user should be prompted to input the pages to be exported, the desired PPI, and output filename.

About the input format for the pages to be exported, I suggest using a comma-separated list of values. Each value could be a single page number, or a closed interval in the form of 'a-b'.

The PPI input should remember the value from the last usage and offer multiples of 144 as selectable options. 

The output directory parameter should be similar to the typst command line parameter format, which is a filename with `{n}`.

**Comment by Myriad-Dreamin** [comment]
Exporting pages with ranges will be allowed in typst v0.12.0
