### ISSUE TITLE
scan context and allow auto import

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Myriad-Dreamin/tinymist#21]
like what rust analyzer does.

**Comment by Myriad-Dreamin** [comment]
![image](https://github.com/Myriad-Dreamin/tinymist/assets/35292584/fc28cc93-f404-4df1-a859-d57fdeb22958)

**Comment by Myriad-Dreamin** [comment]
I thought it useful to have indices on symbols in other files, and use it without need to create an import item manually, like rust-analyzer inserting an use item when you reference some symbols in other crates. But I find it less useful in typst in practice, where you import all symbols in your template and set up preludes as well by a single `#import "template.typ": *`. In your `template.typ` you can do this for example:
```typ
#import "@preview/physica:0.x": *
#import "@preview/t4t:0.x": *
```

**Comment by Andrew15-5** [comment]
Can't you do the same in Rust?
