### ISSUE TITLE
Hope improve the directional links with typst preview extension in vscode

### ISSUE THREAD

**Issue by Super-wyc** [Myriad-Dreamin/tinymist#22]
Now the directional links only can jump to the same paragraph, not the same place, I hope the directional links can be improved.

**Comment by Myriad-Dreamin** [comment]
Do you mean to some improvement about typst preview rather than the tinymist? Or you may mean to tinymist providing some source code information for typst preview extension.

**Comment by Super-wyc** [comment]
I hope a better bidirectional jump experience using tinymist and typst preview. Now the cursor can jump to the same place in .typ, when i click a character in preview, but the cursor won't show in the same character in the preview reversely when click in .typ, I'm not sure tinymist or typst preview which is responsible for this.

**Comment by Myriad-Dreamin** [comment]
> I hope a better bidirectional jump experience using tinymist and typst preview. Now the cursor can jump to the same place in .typ, when i click a character in preview, but the cursor won't show in the same character in the preview reversely when click in .typ, I'm not sure tinymist or typst preview which is responsible for this.

tinymist has not integrated preview features, but it will import the typst preview library. That means any preview feature requirements should be always navigated to typst preview repository. As a collaborator of typst-preview, I can answer preview questions here though.

And back to the real question, does using both tinymist and typst preview break down your experience? I believe typst preview had not made a precise jump from source to preview panel, which should be a point to improve.

**Comment by Super-wyc** [comment]
> > I hope a better bidirectional jump experience using tinymist and typst preview. Now the cursor can jump to the same place in .typ, when i click a character in preview, but the cursor won't show in the same character in the preview reversely when click in .typ, I'm not sure tinymist or typst preview which is responsible for this.
> 
> tinymist has not integrated preview features, but it will import the typst preview library. That means any preview feature requirements should be always navigated to typst preview repository. As a collaborator of typst-preview, I can answer preview questions here though.Tinymist 没有集成预览功能，但它会导入 Typst 预览库。这意味着任何预览功能要求都应始终导航到 typst 预览存储库。作为 typst-preview 的合作者，我可以在这里回答预览问题。
> 
> And back to the real question, does using both tinymist and typst preview break down your experience? I believe typst preview had not made a precise jump from source to preview panel, which should be a point to improve.回到真正的问题，同时使用 tinymist 和 typst 预览会破坏您的体验吗？我相信 typst 预览没有从源代码到预览面板进行精确的跳跃，这应该是一个需要改进的地方。

Tinypist is an excellent typst language server, the precise bidirectional jump is just my expectation for tinymist, which can help me write and check effectively in a large paragraph of text. I hope this would be improved. The issue will be closed, as you already know this.
