### ISSUE TITLE
Inlay hint for `lr` wrongly displays before the first comma

### ISSUE THREAD

**Issue by MDLC01** [Myriad-Dreamin/tinymist#23]
### Describe the bug

In math, within the parentheses of a call to [`lr`](https://typst.app/docs/reference/math/lr#functions-lr), commas are interpreted as content instead of as argument separators by Typst. However, the extension treats them as argument separators. This causes the inlay hint to appear before the first comma.

### To Reproduce

1. Create a new Typst document.
2. Write `$lr(1, 2, 3)$`.
3. Notice how the inlay hint “: body” appears after `1`.

### Expected behavior

The hint should appear before the closing parenthesis, after `3`.

### Package/Software version

tinymist extension version: `v0.10.2`

**Comment by Myriad-Dreamin** [comment]
I will focus all inlay hints improvements after I finishing [Go To Definition/Declaration](https://learn.microsoft.com/en-us/cpp/ide/navigate-code-cpp?view=msvc-170).

**Comment by MDLC01** [comment]
Yes, but only in "smart" mode if I'm not mistaken?

**Comment by MDLC01** [comment]
This is probably unintentionally fixed by #51.

**Comment by Myriad-Dreamin** [comment]
> This is probably unintentionally fixed by #51.

Because it is in smart mode by default.

**Comment by Myriad-Dreamin** [comment]
> This is probably unintentionally fixed by #51.

Oh, I may understand it. I was suggest to place param inlay hints before the params and type inlay hints after some identifier. Do you mean that the wrong position is unintentionally fixed because we will place the hint before the only parameter and after the left bracket anyway?

**Comment by MDLC01** [comment]
Yes this is what I meant.

**Comment by Myriad-Dreamin** [comment]
I'll close it regarding to above discussion.
