### ISSUE TITLE
npm run compile fails in editors/vscode

### ISSUE THREAD

**Issue by astrale-sharp** [Myriad-Dreamin/tinymist#260]
**Describe the bug**
Howdy!
npm run <any script> fails with
```
src/features/symbol-view.detypify.ts:1:26 - error TS2307: Cannot find module '../../assets/detypify/infer.json' or its corresponding type declarations.

1 import inferSymbols from "../../assets/detypify/infer.json";
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Package/Software version:**

tinymist extension version: `v0.11.0#398f2afb043f523ec5b8de84bda0735e3370177b`.
```plain
tinymist 
Build Timestamp:     2024-03-22T02:18:18.207134800Z
Build Git Describe:  v0.11.1-rc2-5-gf0a96cb-dirty
Commit SHA:          398f2afb043f523ec5b8de84bda0735e3370177b
Typst Version:       0.11.0
```

**Comment by Myriad-Dreamin** [comment]
The current CONTRIBUTING guide only includes instructions about developing the binary and the that relates to running editor/vsocde extension locally is missing. I'll add it later.

You can refer the steps in release.yaml before I adding it:

https://github.com/Myriad-Dreamin/tinymist/blob/398f2afb043f523ec5b8de84bda0735e3370177b/.github/workflows/release.yml#L209-L224
