### ISSUE TITLE
Change-request: invert Typst icon for vs-code

### ISSUE THREAD

**Issue by bnjmnjrk** [Myriad-Dreamin/tinymist#278]
_Attention personal taste_
**Motivation**
I often have projects with many Typst files. In my opinion, the Typst icon was designed for recognition rather than for listing files, so the listing of files looks clunky:
![Screenshot from 2024-05-13 12-20-13](https://github.com/Myriad-Dreamin/tinymist/assets/106487517/a72fcff4-2dfb-4257-9de5-acc1eaba2dbc)

If you look at the C or C++ icons, you can see that the "recognition icon" also has a colored background, but in vs code it has a much lighter design.
e.g. from [c++ recognition icon](https://github.com/isocpp/logos?tab=readme-ov-file)
 to 
![Screenshot from 2024-05-13 12-25-05](https://github.com/Myriad-Dreamin/tinymist/assets/106487517/433f60a5-0e15-40cb-a0f6-939cbc054e50)

How would you like it if we also inverted the Typst icon? It could look like this:
![Screenshot from 2024-05-13 12-19-47](https://github.com/Myriad-Dreamin/tinymist/assets/106487517/b37403b9-10eb-4ffc-a0f2-39cc972473e4)

**Comment by Myriad-Dreamin** [comment]
I think we need some votes on it. I personally doesn't have that feeling. But imo it is better to make it smaller and move right a bit.

**Comment by Myriad-Dreamin** [comment]
Using the icon from https://github.com/simple-icons/simple-icons/pull/10399

![image](https://github.com/Myriad-Dreamin/tinymist/assets/35292584/0d6082ad-b9a7-4f3d-8154-71cea867a1fb)
