### ISSUE TITLE
Annotate code example as Typst code

### ISSUE THREAD

**Issue by Iorvethe** [Myriad-Dreamin/tinymist#284]
**Motivation**

Annotating code snippets as Typst code in Markdown docs would make them correctly highlighted by Treesitter’s injection queries.

**Description**

I use Helix and currently when requesting docs for an item, code snippets inside aren’t highlighted as Typst code. I do not know whether the issue is with annotating the code or something else, but I suppose it is something in that vein. When writing Markdown and including a Typst snippet, it is correctly highlighted for example.

**Examples/Questions**

| Hover Docs | Markdown|
|- | - |
|![image](https://github.com/Myriad-Dreamin/tinymist/assets/58810330/3cf317ae-fab0-4baf-bbb6-da2a0d7dc865) | ![image](https://github.com/Myriad-Dreamin/tinymist/assets/58810330/355bf776-bd79-46d8-9516-1eb57760e18c) |

**Comment by Myriad-Dreamin** [comment]
I noticed that. The embedded document marks these code as `example` language, so we need a preprocessor to mark them all as `typst` language. This needs some effort.

https://github.com/typst/typst/blob/2d32ac73b63c81ea2754916feb7758c042f4ed3d/crates/typst/src/math/equation.rs#L31-L42

````rs
/// ```example
/// #set text(font: "New Computer Modern")
///
/// Let $a$, $b$, and $c$ be the side
/// lengths of right-angled triangle.
/// Then, we know that:
/// $ a^2 + b^2 = c^2 $
///
/// Prove by induction:
/// $ sum_(k=1)^n k = (n(n+1)) / 2 $
/// ```
````
