### ISSUE TITLE
Properly move puncutation when toggling block equation

### ISSUE THREAD

**Issue by lukasjuhrich** [Myriad-Dreamin/tinymist#305]
**Motivation**

Being able to toggle between inline and block equations is tremendously useful.
However, when turning an inline equation like `$f in cal(O)(n, k)_l = n^l -> k$,` into a block equation,
the result is
```typst
$ f in cal(O)(n, k)_l = n^l -> k $,
```
which looks awkward due to the trailing comma. I have to fix that manually after toggling the action, which slightly diminishes the benefit of having the code action in place.

**Description**
Move trailing punctuation into the equation when toggling block mode, and back outside when toggling inline mode.

**Comment by Myriad-Dreamin** [comment]
That sounds definitely an improvement, but I have a detail to tune. That is we may not move the last punctuation inside of a block equation outside when converting equation to inline style, which depends on personal preference.

```
// From
$ alpha, $
// To (Opt. 1)
$alpha,$
// Or (Opt. 2)
$alpha$,
```

I'm not sure which one is better, but I feel it is another corner cases and I'm keeping stupid to do nothing (Opt. 1).
