### ISSUE TITLE
Autocompletion of bibliography styles that aren't built in

### ISSUE THREAD

**Issue by Enivex** [Myriad-Dreamin/tinymist#308]
**Motivation**
I have "beststyleever.csl" in the same folder as my typst document, but it does not appear as a choice for autocompletion for the style parameter of `bibliography` or `cite`.

**Description**
Make it appear ;)

**Comment by Myriad-Dreamin** [comment]
Currently, we filter the files by suffixes:
- `.yaml`
- `.yml`
- `.bib`

Perhaps we will have some other missing suffixes to add.

https://github.com/Myriad-Dreamin/tinymist/blob/247c6d584876217834a59550fb3719d9c38443af/crates/tinymist-query/src/ty/builtin.rs#L46-L47

**Comment by Enivex** [comment]
> Currently, we filter the files by suffixes:
> - `.yaml`
> - `.yml`
> - `.bib`
> 
> Perhaps we will have some other missing suffixes to add.
> 
> https://github.com/Myriad-Dreamin/tinymist/blob/247c6d584876217834a59550fb3719d9c38443af/crates/tinymist-query/src/ty/builtin.rs#L46-L47
> 
> 

- But that's for the bibliography itsel. I'm specifically talking about the style (*.CSL)

**Comment by Enivex** [comment]
> > Currently, we filter the files by suffixes:
> > - `.yaml`
> > - `.yml`
> > - `.bib`
> > 
> > Perhaps we will have some other missing suffixes to add.
> > 
> > https://github.com/Myriad-Dreamin/tinymist/blob/247c6d584876217834a59550fb3719d9c38443af/crates/tinymist-query/src/ty/builtin.rs#L46-L47
> > 
> > 
> 
>

 But that's for the bibliography itsel. I'm specifically talking about the style (*.CSL)
