### ISSUE TITLE
fontPaths config in Helix doesn't seem to find the fonts for autocomplete

### ISSUE THREAD

**Issue by sbromberger** [Myriad-Dreamin/tinymist#309]
**Describe the bug**
Using helix with the following config:
```
[language-server.tinymist]
command = "tinymist"
config = {fontPaths = ["/path/to/my/fonts"]}
```
and subdirectories containing fonts in `/path/to/my/fonts`, I do not see these fonts in the autocompletion list when I type `#set text(font: ` . I see the default ones.

I would expect to see the fonts listed similar to what`typst fonts --font-path /path/to/my/fonts` produces.

Using `config = {typstExtraArgs = ["--font-path", "/path/to/my/fonts"]}` works as expected (the fonts in that directory tree are in the autocomplete list).

**Package/Software version:**

```plain
tinymist 
Build Timestamp:     2024-05-20T20:04:51.425277910Z
Build Git Describe:  v0.11.9-1-g247c6d5
Commit SHA:          247c6d584876217834a59550fb3719d9c38443af
Commit Date:         None
Commit Branch:       None      
Cargo Target Triple: x86_64-unknown-linux-gnu
Typst Version:       0.11.1
```

with `helix 24.3 (e76020dd)`

**Comment by Myriad-Dreamin** [comment]
The `fontPaths` configuration is processed in VSCode extension, but it is better to be processed in lsp server to get helix work with it.

**Comment by sbromberger** [comment]
I'm not sure I understand. I followed the instructions for Helix which, in ["Extra Settings"](https://github.com/Myriad-Dreamin/tinymist/blob/main/editors/helix/README.md#extra-settings), led me to [the configuration document](https://github.com/Myriad-Dreamin/tinymist/blob/main/editors/neovim/Configuration.md#fontpaths) that describes fontPaths.

Are you saying that the fontPaths configuration is not used by the helix lsp server? If so, that's fine - the workaround is to use `typstExtraArgs`. No big deal, but wanted to check. :)

Thank you very much for this great lsp server. It's made learning typsd much easier!

**Comment by Myriad-Dreamin** [comment]
> Are you saying that the fontPaths configuration is not used by the helix lsp server?
Yes, and it is not intended. The fontPaths configuration was made in early development when I didn't consider clients other than vscode. I'll fix it once I schedule time.

**Comment by sbromberger** [comment]
Ah, I totally understand! OK. Let me know if you would like me to test a potential implementation. Happy to help wherever I can.

**Comment by sbromberger** [comment]
Wow, that was super fast. Thank you! Can't wait to try it.

**Comment by sbromberger** [comment]
Confirmed working! Thanks again.

Also, something to ponder:
```
$ cargo build --release            
$ cp target/release/tinymist ~/.local/bin
$ ls -l ~/.local/bin/tinymist 
-rwxr-x--- 1 seth seth 567367792 May 23 09:03 /home/seth/.local/bin/tinymist*
$ strip ~/.local/bin/tinymist 
$ ls -l ~/.local/bin/tinymist
-rwxr-x--- 1 seth seth 46939440 May 23 09:03 /home/seth/.local/bin/tinymist*
```

I would've thought `--release` would strip, but in any case, you can save half a gig(!) by stripping the binary.

**Comment by Myriad-Dreamin** [comment]
> Confirmed working! Thanks again.
> 
> Also, something to ponder:
> 
> ```
> $ cargo build --release            
> $ cp target/release/tinymist ~/.local/bin
> $ ls -l ~/.local/bin/tinymist 
> -rwxr-x--- 1 seth seth 567367792 May 23 09:03 /home/seth/.local/bin/tinymist*
> $ strip ~/.local/bin/tinymist 
> $ ls -l ~/.local/bin/tinymist
> -rwxr-x--- 1 seth seth 46939440 May 23 09:03 /home/seth/.local/bin/tinymist*
> ```
> 
> I would've thought `--release` would strip, but in any case, you can save half a gig(!) by stripping the binary.

I left a comment in the PR

**Comment by Myriad-Dreamin** [comment]
> Wow, that was super fast. Thank you! Can't wait to try it. (Possible to get a new version tagged?)

Tinymist is released per week. You can still install it by cargo or download nightly prebuilt on GitHub actions.
