### ISSUE TITLE
No evaluation for default value previews

### ISSUE THREAD

**Issue by miliog** [Myriad-Dreamin/tinymist#311]
**Describe the bug**
For variables and dictionary entries, it returns `any`, and for function calls, it returns `none`. I'm not sure if this can even be solved easily, but instead of those values, it should at least return `unknown` or something similar.

![image](https://github.com/Myriad-Dreamin/tinymist/assets/146289769/4cb1a675-3dc0-4022-8a6c-5bffd9e307a3)

**Package/Software version:**

VSCode version(Help -> About):
```
Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
```

tinymist extension version: `v0.11.9`

**Comment by Myriad-Dreamin** [comment]
they are just not implemented features. I'll implement them in next round of development.
