### ISSUE TITLE
Fail to recognize bib items when multiple files involve

### ISSUE THREAD

**Issue by Devin-Yeung** [Myriad-Dreamin/tinymist#321]
**Describe the bug**

Tinymist fail to identify the bib items when multiple files involves. For example, if `#bibliography("ref.bib")` is in `main.typ` and `content.typ` is `#include` by `main.typ`, the bib items are only available in `main.typ` but not available in `content.typ`.

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.89.0 (Universal)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:10:10.196Z (1 mo ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.0.0
```

tinymist extension version: `v0.11.10`. Get it by `tinymist --version` in terminal.
```plain
tinymist
Build Timestamp:     2024-05-26T03:55:31.206765000Z
Build Git Describe:  v0.11.10
Commit SHA:          eb12ef0671adb1e1e09e6e99facbfa46f96a6ed7
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: aarch64-apple-darwin
Typst Version:       0.11.1
```

**Additional context**

Here are the steps to reproduce the bug:

directory structure:

```
.
├── ref.bib
├── content.typ
├── main.typ
```
Source code for `ref.bib`
```
@phdthesis{madje2022typst,
  title  = {A Programmable Markup Language for Typesetting},
  author = {M{\"a}dje, Laurenz},
  year   = {2022},
  school = {2022}
}
```

Source code for `main.typ`

```typ
// main.typ
#include "content.typ"
#bibliography("ref.bib", full: true)
```

Source code for `content.typ`
```typ
// content.typ
@madje2022typst // lsp gives an error: label `<madje2022typst>` does not exist in the document
```

**Comment by Myriad-Dreamin** [comment]
You need to pin the main file so that the entry file doesn't change when you switch files.

Hint: typst-preview supports to pin it when you start to preview some file. https://github.com/Enter-tainer/typst-preview/blob/main/addons/vscode/package.json#L224

**Comment by Devin-Yeung** [comment]
> You need to pin the main file so that the entry file doesn't change when you switch files.

This works for me, thank you! Btw, I am curious about how can I achieve this if I use other editors (e.g Zed / neovim) which does not support typst-preview. Does tinymist provide any option to pin the main file?

**Comment by Myriad-Dreamin** [comment]
> > You need to pin the main file so that the entry file doesn't change when you switch files.
> 
> This works for me, thank you! Btw, I am curious about how can I achieve this if I use other editors (e.g Zed / neovim) which does not support typst-preview. Does tinymist provide any option to pin the main file?

No best model currently, they can set an entry file by configuration globally or in workspace.

https://github.com/Myriad-Dreamin/tinymist/tree/main/editors/vscode#passing-extra-cli-arguments

**Comment by Devin-Yeung** [comment]
Thank you for your time answering this, I think I can mark this issue as solved

**Comment by peekxc** [comment]
This didn't work for me unfortunately

**Comment by fourdim** [comment]
For those who need to pin the main file in the recent version of Tinymist.
Use `ctrl+shift+p` and type `Pin the Main file to the Opening Document` to pin the main file.
Or alternatively, preview the main file. Tinymist will automatically pin it for you.

**Comment by mattyoung101** [comment]
For those using Neovim, after much effort I came up with the following:

```lua
local function tinymistPinMain(path)
    -- For some reason, this doesn't work; exec_cmd is nil. We have to use buf_request directly.
    -- local tinymist_options = vim.lsp.get_clients({name = "tinymist"})
    -- if next(tinymist_options) == nil then
    --     print("Tinymist is not active.")
    --     return
    -- end
    -- local tinymist = tinymist_options[1]
    -- print("Found Tinymist client")
    -- tinymist:exec_cmd({
    --     command = "tinymist.pinMain",
    --     arguments = { path }
    -- })
    vim.lsp.buf_request(0, "workspace/executeCommand", {
        command = "tinymist.pinMain",
        arguments = { path },
    }, function(err, _, _)
        if err then
            vim.notify("Error executing tinymist.pinMain: " .. err.message, vim.log.levels.ERROR)
        else
            vim.notify("Command tinymist.pinMain executed successfully", vim.log.levels.INFO)
        end
    end)
end
```

You can then bind this to a user command:

```lua
vim.api.nvim_create_user_command("PinThesisMain", function()
    tinymistPinMain("somePath")
end, {})
```

Then, you just have to invoke `:PinThesisMain` once per session. 

It's not clear to me why calling `exec_command` doesn't work, it might be something on the Tinymist side. In any case, `buf_request` works fine and doesn't seem to interfere with other LSPs.

**Comment by schluis** [comment]
This didn't work for me, but I found another nice solution:

```lua
vim.api.nvim_create_user_command("TypstPin", function()
  local tinymist_id = nil
  for _, client in pairs(vim.lsp.get_active_clients()) do
    if client.name == "tinymist" then
      tinymist_id = client.id
      break
    end
  end

  if not tinymist_id then
    vim.notify("tinymist not running!", vim.log.levels.ERROR)
    return
  end

  local client = vim.lsp.get_client_by_id(tinymist_id)
  if client then
    client.request("workspace/executeCommand", {
      command = "tinymist.pinMain",
      arguments = { vim.api.nvim_buf_get_name(0) },
    }, function(err)
      if err then
        vim.notify("error pinning: " .. err, vim.log.levels.ERROR)
      else
        vim.notify("succesfully pinned", vim.log.levels.INFO)
      end
    end, 0)
  end
end, {})
```

Calling `:TypstPin` then pins the current buffer
This also works with other clients

**Comment by a-berg** [comment]
Problem persists even after pinning (using Helix 25.01.1 which can invoke lsp-workspace-command)
