### ISSUE TITLE
[Frontend] Autocompletion with correct quote pairing

### ISSUE THREAD

**Issue by KagaJiankui** [Myriad-Dreamin/tinymist#324]
**Motivation**

Handle the string autocompletion inside quotes correctly.

**Description**

The autocompletion feature provided by the `Tinymist` extension is unable to handle the "partial completion" scenarios especially when inside or after quotes.

For example, an font family name string is quoted as the first figure shows:

![image](https://github.com/Myriad-Dreamin/tinymist/assets/58453886/43c0787b-e8d5-4d07-8506-3accfb2b1a7a)

The autocompletion entries after the cursor simply provides the full word surrounded with closed quotes, rather than the remaining part of the word, like this:

```plain
"ST|____
   -Song"
   -Xihei"
   -Xingkai"
   -...
```

With the provided entries, the autocompletion functionality is not readily compilable at tab keystroke, but requires manual semantic correction to remove the redundant non-closing quote:

![image](https://github.com/Myriad-Dreamin/tinymist/assets/58453886/06ebd973-8022-45b2-aba0-eaaecb7e9b9c)

**Comment by Myriad-Dreamin** [comment]
I don't have much time, but I'm also wondering whether it works in older version. The current LSP doesn't handle "partial completion" well. It does/doesn't add pairs by judgements here and there. I believe it could be solved by improving the "arch" of completion for completion within label/string/raw.

**Comment by Myriad-Dreamin** [comment]
I cannot reproduce it. Could you provide detailed steps to trigger it?

**Comment by KagaJiankui** [comment]
Sorry for troubling you after the issue is closed, but the bug still exists with the newest build. Under the case that the completion (suggestion) is **explicitly** triggered by key shortcuts, for example `tab` or `Ctrl+Space`, as shown in the following picture:

***@***.***

The auto completion still suggests full string with incorrect pairing of quotes.

Under the auto suggestion scenarios, the bug is mitigated, however there are opportunities that the font suggestion is unable to pop out. Inside the typst string, the auto suggestion needs to be triggered explicitly by key shortcuts, or delete the whole string including the quote and type again.

发件人: Myriad-Dreamin ***@***.***>
发送时间: 2024年6月27日 18:31
收件人: Myriad-Dreamin/tinymist ***@***.***>
抄送: Falken Sakurai ***@***.***>; Author ***@***.***>
主题: Re: [Myriad-Dreamin/tinymist] [Frontend] Autocompletion with correct quote pairing (Issue #324)


Closed #324<https://github.com/Myriad-Dreamin/tinymist/issues/324> as completed via #351<https://github.com/Myriad-Dreamin/tinymist/pull/351>.

**Comment by Myriad-Dreamin** [comment]
You should delete content of a half completing font and retrigger it again.
