### ISSUE TITLE
Duplicate quote when auto completing fonts

### ISSUE THREAD

**Issue by Enter-tainer** [Myriad-Dreamin/tinymist#339]
**Describe the bug**

starting here with cursor placing at `!`, and press `"`, the auto complete menu should appear
```typst
#set page(height: auto, width: auto)
#set text(lang: "zh", region: "cn", font: (!))
```

![image](https://github.com/Myriad-Dreamin/tinymist/assets/25521218/b8e9d80c-ac95-446a-a6e8-886db8e112a9)

Select any of them, we can see the quote is duplicated

![image](https://github.com/Myriad-Dreamin/tinymist/assets/25521218/9ba5ab87-3d3e-44dd-8d61-267b1a8d7cad)

**Package/Software version:**

tinymist extension version: v0.11.11

**Comment by Myriad-Dreamin** [comment]
same issue as #324
