### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: NotFound

### ISSUE THREAD

**Issue by Niedzwiedzw** [Myriad-Dreamin/tinymist#355]
[2024-07-01T08:38:43Z DEBUG typst_preview::actor::render] RenderActor: waiting for message
thread '<unnamed>' panicked at /home/niedzwiedz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reflexo-world-0.5.0-rc5/src/world.rs:476:14:
called `Result::unwrap()` on an `Err` value: NotFound("/home/niedzwiedz/firma-niedzwiedz/pisma/2024/2024-07-01--wezwanie-do-okazania-umow-i-dowodow-swiadczenia-uslug-odpadow/main.typ")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Rayon: detected unexpected panic; aborting
[1]    1862080 IOT instruction (core dumped)  tinymist preview ./main.typ

**Comment by Myriad-Dreamin** [comment]
Does it always happen in your workspace?

**Comment by Niedzwiedzw** [comment]
it's a simple project I just created and it happens after couple edits

**Comment by Niedzwiedzw** [comment]
```
$ tinymist --version
tinymist
Build Timestamp:     2024-07-01T08:10:47.430315601Z
Build Git Describe:  230b36d
Commit SHA:          230b36de4b608d0fa4db90ed20777c470b1fc80a
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-unknown-linux-gnu
Typst Version:       0.11.1
```

**Comment by Niedzwiedzw** [comment]
there's also this in the warnings:
```
[2024-07-01T10:06:46Z WARN  typst_ts_compiler::watch] same content but mtime is different...: "/home/niedzwiedz/firma-niedzwiedz/pisma/2024/2024-07-01--wezwanie-do-okazania-umow-i-dowodow-swiadczenia-uslug-odpadow/main.typ" content: prev:Bytes(0) v.s. curr:Bytes(851)
```

**Comment by Myriad-Dreamin** [comment]
Unsure whether the PR fixed it. Feel free to reopen it if it is not fixed.
