### ISSUE TITLE
Syntax highlighting issue in VS Code with specific text pattern.

### ISSUE THREAD

**Issue by maxchang3** [Myriad-Dreamin/tinymist#356]
**Describe the bug**

```typ
SET 1
11
11
```
![6777b7fe7471e2da13680ac93d782c0b](https://github.com/Myriad-Dreamin/tinymist/assets/36927158/4c7b235f-01e8-4702-84d6-00892d61f07b)

```typ
SET 1
11
11
```

![ce9dc03ad78a1e19c79cb86853caec60](https://github.com/Myriad-Dreamin/tinymist/assets/36927158/63a6b9a0-1181-4f3b-b6fb-c03e3444a26e)

Notice that the highlighting is incorrect after the `SET` occurs.

**Package/Software version:**

tinymist extension version: `v0.11.0`. Get it by `tinymist --version` in terminal.
```plain
# ~/.vscode/extensions/myriad-dreamin.tinymist-0.11.11-darwin-arm64/out [17:04:27] C:127
$ ./tinymist --version
tinymist
Build Timestamp:     2024-06-17T05:49:00.977859000Z
Build Git Describe:  v0.11.11
Commit SHA:          1c653d5fd28706e27077f8a2d49e6e7f072c2bb2
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: aarch64-apple-darwin
Typst Version:       0.11.1

Name: Tinymist Typst
Id: myriad-dreamin.tinymist
Description: An integrated language service for Typst
Version: 0.11.12
Publisher: Myriad Dreamin

```

**Comment by Myriad-Dreamin** [comment]
I cannot reproduce it.

![image](https://github.com/Myriad-Dreamin/tinymist/assets/35292584/4478b6e2-1f2c-4320-a94d-526261b6b079)

![image](https://github.com/Myriad-Dreamin/tinymist/assets/35292584/80a0a3f5-2cfd-4b19-9e4f-70fa2424a63e)

**Comment by maxchang3** [comment]
Sorry for wasting your time. Initially, I used Extension Bisect and only identified tinymist. Later, I noticed that other MySQL keywords (such as CREATE, ALTER, DROP) also caused similar issues, which reminded me that I had installed an SQL-related extension, Highlight String Code (iuyoy.highlight-string-code). After disabling it, the problem was resolved.
