### ISSUE TITLE
Tinymist eating large amounts of RAM

### ISSUE THREAD

**Issue by aesthesa** [Myriad-Dreamin/tinymist#419]
**Describe the bug**
I am working on a ~20 page document with a bunch of CeTZ-illustrations, and Tinymist (using the live preview functionality) takes up as much as ~4 GiB of memory.
It goes to the point where my system with 8 GB of RAM freezes if I try to open a browser alongside VSCode.

Sadly I don't have the time right now to investigate the causes in detail, so I am posting this only to bring it up.

Has anyone else experienced the issue? Or is this to be expected even?

**Package/Software version:**

tinymist extension version: `v0.11.0`. Get it by `tinymist --version` in terminal.
```plain
tinymist
Build Timestamp:     2024-07-15T03:08:38.386657570Z
Build Git Describe:  v0.11.15
Commit SHA:          b8de9f9553bbfcb2d28210b260aa1fcdb1f089b0
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-unknown-linux-gnu
Typst Version:       0.11.1
```

**Comment by Myriad-Dreamin** [comment]
It depends. Quick things to check which one is the evil:
- Lsp Uses: RAM used by lsp update without previewing.
- Preview Uses: RAM used by standalone command `tinymist preview` update.
- Compiler Uses: RAM used by `typst-cli` watching update.
- Old Preview Uses: RAM used by old typst-preview update.

**Comment by AlCap23** [comment]
I am using VSCode while traveling, so Terminal debugging is difficult but here ist the output of the activity monitor

<img width="793" alt="image" src="https://github.com/user-attachments/assets/33f79bd2-3591-4d17-9995-d30886d19d67">

Its a presentation with 3 fletcher graphs and overall 24 slides.

**Comment by Myriad-Dreamin** [comment]
The stats doesn't help because we don't know which part is consuming memory (LSP, preview, or compiler itself).

> Its a presentation with 3 fletcher graphs and overall 24 slides.

fwiw, both cetz and polylux are heavy and use much memory. But it also depends on the complexity of your document (may be unintentionally).

**Comment by Myriad-Dreamin** [comment]
> It depends. Quick things to check which one is the evil:
> 
> * Lsp Uses: RAM used by lsp update without previewing.
> * Preview Uses: RAM used by standalone command `tinymist preview` update.
> * Compiler Uses: RAM used by `typst-cli` watching update.
> * Old Preview Uses: RAM used by old typst-preview update.

Close since it is unclear which specific ones are consuming RAM.

**Comment by memeplex** [comment]
I'm experiencing a similar problem. Activity monitor shows ~3GB mem usage for tinymist. It's a polylux document using the simple theme with some tweaks, I guess I could easily get rid of polylux since I'm not using any dynamic feature. There is a cetz plot but I have commented it out and the problem persists. Also many svg images I produced with Excalidraw. And a lot of math. But all in all a pretty regular document.

[Clase 2 - Intro Proba.zip](https://github.com/user-attachments/files/16536384/Clase.2.-.Intro.Proba.zip)

**Comment by memeplex** [comment]
<img width="655" alt="image" src="https://github.com/user-attachments/assets/4c4aabcf-ce84-4119-bc39-390d18a7407a">


That process seems to be the LSP:

```
❯ ps -fe | grep tiny
  501 22905 22901   0  9:37PM ??         0:00.29 /Users/carlos/.vscode/extensions/myriad-dreamin.tinymist-0.11.18-darwin-arm64/out/tinymist lsp
  501 22913 22903   0  9:37PM ??         1:37.93 /Users/carlos/.vscode/extensions/myriad-dreamin.tinymist-0.11.18-darwin-arm64/out/tinymist lsp
```

**Comment by memeplex** [comment]
A couple of extra details:
- It doesn't start like that but quickly scales up in a few minutes.
- I tried disabling the experimental partial rederer, but to no avail.
- Other than that, it's the default tinymist config.

**Comment by Enter-tainer** [comment]
> It depends. Quick things to check which one is the evil:
> - Lsp Uses: RAM used by lsp update without previewing.
> - Preview Uses: RAM used by standalone command `tinymist preview` update.
> - Compiler Uses: RAM used by `typst-cli` watching update.
> - Old Preview Uses: RAM used by old typst-preview update.

@memeplex please provide these metrics so we can better diagnose this issue

**Comment by memeplex** [comment]
I've provided all that's available, including the full source document. The offending process is `tinymist lsp` as shown in the output from `ps` above.

Anyway, after some cursory profiling, I believe it's the previewer. Working for a while without any preview prevented the scaling up of memory usage. While updating the preview on save (not on type) slowed it down but ultimately it built up to the same point.

**Comment by memeplex** [comment]
If you want another metric I've not problem in providing it to you, but please specify the procedure in a more detailed manner. For example, 

> Preview Uses: RAM used by standalone command tinymist preview update.

do you want me to continuously run `tinymist preview` from the command line?
