### ISSUE TITLE
Zoom or margin clipping in preview

### ISSUE THREAD

**Issue by harrysw1729** [Myriad-Dreamin/tinymist#428]
**Motivation**

Previews leave horizontal margins in the preview pane, which competes for screen space against other vs code panes. A feature that could trim the margins of the preview pane would be really nice. 😃 

Thank you very much for your consideration.

**Comment by Myriad-Dreamin** [comment]
I feel we can utilize `sys.inputs` to let template aware of you are previewing and editing the document, which will help reduce margins perfectly, while lsp cannot know the margin to reduce well.

If we add a variable like `sys.inputs.preview`, we can do that:

```typ
#let is-previewing = sys.inputs.at("preview", default: none) != none;
#let template = it => {
  // Reduce margin if previewing
  set page(margin: 0.1em) if is-previewing
  it
}
```

**Comment by harrysw1729** [comment]
Thanks for implementing the feature in the new update!

However, it appears that it interferes with the PDF export feature of the vs code extension: When I run `Typst: Export the currently open file as PDF` from the command palette, the exported PDF would also use the set-rule set by `template`. A workaround seems to be manually running `typst compile`.

**Comment by Myriad-Dreamin** [comment]
Thank you for your feedback. This looks like a significant insight to go down on this feature. We may add the preview argument only if when we are previewing documents.
