### ISSUE TITLE
Typst preview lags behind

### ISSUE THREAD

**Issue by ziiirozone** [Myriad-Dreamin/tinymist#455]
When previewing my typst document, half of the time the last changes (last typed letters) doesn't appear, no matter how much time I wait, and when it happens the preview doesn't react when I click on a word to teleport to it. This seems to only happen when I am previewing a large document, mine is a math paper of around 50 pages purely in typst, no external packages, and a dozen of svg, the rest is text/math. I didn't have this issue in the now deprecated "typst preview" extension.

VSCode version :
```plain
Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:08:12.169Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.1.0-23-amd64
```

tinymist extension version: `v0.11.16`

Thanks for your work, this is the only issue I have been having and the rest is perfect !

**Comment by Myriad-Dreamin** [comment]
The underlying code has changed a lot recently. I'm seeing how to trigger it reliably, to prevent future regression.

**Comment by Myriad-Dreamin** [comment]
I didn't find a good test to cover this bug, but it will not prevent PR from merging.

**Comment by ziiirozone** [comment]
The issue seems to be fixed on my end in the last update, many thanks for the fix ! Can't type in typst without previewing the document, such a good feature !
