### ISSUE TITLE
No Content-Type header on static html

### ISSUE THREAD

**Issue by cskeeters** [Myriad-Dreamin/tinymist#463]
I was testing using this in github Codespaces and the browser just showed the text of the HTML.  After some debugging, I noticed that `Content-Type` header is not included in the response.  The static web server should probably send responses with `Content-Type` set to `text/html`.

After browsing through the code a bit, it looks like `hyper::Response::new` [is used](https://github.com/Myriad-Dreamin/tinymist/blob/22aea0e0752494c52c14d1503004a311b549b144/crates/tinymist/src/tool/preview.rs#L372C64-L372C67).

...instead of `Response::builder()`, which might look something like

```
let response = Response::builder()
    .header("Content-Type", "text/html")
    .header("Content-Length", body.len())
    .body(body.into())
    .unwrap();
```

**Comment by Enter-tainer** [comment]
Nice catch! Would you like open a PR and fix this?

**Comment by Enter-tainer** [comment]
BTW, due to #382, preview may not work in vscode web or similar things.

**Comment by cskeeters** [comment]
To my surprise, I got tinymist (with my fix) to work with GitHub Codespaces.  If you forward all three ports, then you can access the preview locally with `http://localhost:23627/`.

    gh cs ports forward 23625:23625 23626:23626 23627:23627
