### ISSUE TITLE
How do I preview pdf using tinymist in neovim?

### ISSUE THREAD

**Issue by kamransoomro84** [Myriad-Dreamin/tinymist#475]
I have configured tinymist in neovim and the Hover and snippets are working. But I cannot figure out how to preview my pdf using tinymist like I can do in vscode?

**Comment by Myriad-Dreamin** [comment]
set export mode to onType and open the exported pdf in your the favorite viewer.

**Comment by kamransoomro84** [comment]
It already is set to onType but isn't working apparently. Also does this mean that there's no scrollsyncing like in the vscode extension?

**Comment by Myriad-Dreamin** [comment]
> It already is set to onType but isn't working apparently.

I don't know it and there is no related report since recent months. If there is a bug please send the concrete log.

> Also does this mean that there's no scrollsyncing like in the vscode extension?

For pdf preview, no. But you could set up https://github.com/chomosuke/typst-preview.nvim.

**Comment by Eric-Song-Nop** [comment]
I followed the config suggestions provided (by the author)[https://github.com/Myriad-Dreamin/tinymist/blob/main/editors/neovim/README.md#configuring-lsp-server] with lazyvim, and it turns out that the setting in `settings = {...}` is not read by the language server at all

**Comment by Eric-Song-Nop** [comment]
I can confirm that the settings from lspconfig is not read by tinymist server.

**Comment by Eric-Song-Nop** [comment]
I tested with a vanilla lazyvim with exact same setup as documentation, but I add some log after initialization for tinymist, while the exportPdf setting is always set to "never"

**Comment by kamransoomro84** [comment]
> I tested with a vanilla lazyvim with exact same setup as documentation, but I add some log after initialization for tinymist, while the exportPdf setting is always set to "never"

What's your config like? I managed to get it to work.

**Comment by Eric-Song-Nop** [comment]
I followed this setting and tinymist is definitely attached, but it is still not working. but I guess there is something wrong with lazyvim or my sesttings, as I can make it work in a lunarvim setup

**Comment by Eric-Song-Nop** [comment]
I realized that is was my `ufo` config conflict with it, it is totally my fault, sorry for taking your time, please ignore eveything from me

**Comment by Myriad-Dreamin** [comment]
they are already here: https://myriad-dreamin.github.io/tinymist/frontend/neovim.html#label-Configuring%20LSP%20Server.
