### ISSUE TITLE
Neovim `preview` setting

### ISSUE THREAD

**Issue by ioplju** [Myriad-Dreamin/tinymist#484]
I don't understand what is the [`preview` setting](https://github.com/Myriad-Dreamin/tinymist/blob/main/editors/neovim/Configuration.md#preview).

The `preview` setting documentation indicates it's a string but there are `preview.X` settings too which indicates that `preview` is also a table.

**Comment by Myriad-Dreamin** [comment]
You can ignore them. They are configurations generated from https://github.com/Myriad-Dreamin/tinymist/blob/main/editors/vscode/package.json. I'll remove them from neovim documentation.

If you are looking for the preview feature, you could check [typst-preview.nvim](https://github.com/chomosuke/typst-preview.nvim), utilizing `tinymist preview` command.
