### ISSUE TITLE
Support folding region markers

### ISSUE THREAD

**Issue by memeplex** [Myriad-Dreamin/tinymist#506]
**Motivation**

Folding the entire "preamble" or subdividing it in logically folded regions, allows to hide presentation logic from content and to better organize supporting code.

Moreover, the logical structure of the document as perceived by the author may not exactly match the structure as seen by the folding function.

**Description**

Provide support for explicit folding with region markers.

Many languages provide `region` and `endregion`-style markers for user defined folding, as described in:

https://code.visualstudio.com/docs/editor/codebasics#_folding

**Example**

```
// region Packages
...
// endregion

// region Funcions
...
// endregion
```

**Workaround**

It is also possible to [define a fold from selection](https://code.visualstudio.com/docs/editor/codebasics#_fold-selection), although I assume it's lost with the workspace.

**Comment by Myriad-Dreamin** [comment]
It may conflict with future syntax of typst such as decorators in comment, so you should discuss the legality of region markers first in [typst/typst](https://github.com/typst/typst) or the discord server.

**Comment by memeplex** [comment]
I understand, but any current comment may conflict with future syntax inside comments, and they are 100% free.

**Comment by Myriad-Dreamin** [comment]
The biggest obstacle is how typst regards comments as decorators and documentation, the region marker syntax may already conflict with them.
