### ISSUE TITLE
Incremental compilation significantly slower than full compilation in preview mode

### ISSUE THREAD

**Issue by hooyuser** [Myriad-Dreamin/tinymist#529]
**Describe the bug**
For my current Typst project, I've observed that in preview mode, after editing for about 1-2 minutes, incremental compilation becomes significantly slower than a full compilation.

Here is one of my experiments (tinymist server log [tinymist_log.txt](https://github.com/user-attachments/files/16592509/tinymist_log.txt))
- The initial full compilation time is 6.31 seconds (measured by `typst_ts_compiler::diag::console`).
- After some random cut-and-paste operations, the 35th incremental compilation takes 36.39 seconds.
- After saving and reopening, a full compilation takes about 6.28 seconds.

The sample file contains 34 pages. I tried reducing it to 18 pages by commenting out the rest, but the problem persists. (full compilation: ~3 seconds,  incremental compilation: ~15 seconds)

Additionally, I've noticed that the memory usage gradually increases. With 32 GB of RAM on my machine, it can consume up to 26 GB, with the memory usage monitor showing 98% utilization. After that there may be some memory swapping, though it is not necessarily relevent to this issue.

**Steps to Reproduce:**
- Download my project [debug.zip](https://github.com/user-attachments/files/16592483/debug.zip)
- Set the font path with --font-path fonts.
- Open debug.typ and preview it.
- Perform random cut-and-paste operations with small code snippets like `cal(P)_QQ` from one formula to another.
- Observe the compilation time in the output. As time goes by, minor modifications can result in a laggy refresh and lead to an incremental compilation time that is several times longer than a full compilation.
- Close VSCode and reopen the file. The compilation time returns to normal (~6 seconds on my machine).

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.92.1 (user setup)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045
```

tinymist extension version: `v0.11.0`. Get it by `tinymist --version` in terminal.
```plain
tinymist
Build Timestamp:     2024-08-11T06:20:09.984297300Z
Build Git Describe:  v0.11.19
Commit SHA:          606486b9fd64d117880578477c0188a136094db1
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-pc-windows-msvc
Typst Version:       0.11.1
```

**Comment by Myriad-Dreamin** [comment]
This looks insightful. If it is reproducible on my machine, I can write some script to gather fine-grained memory and perf stats after it is edited for several times. I may do it in this week.

**Comment by hooyuser** [comment]
To reproduce the issue, I've found that modifying the performance-intensive sections of my project, such as `#functor_diagram(F:..., G:..., ...)`, makes the issue more noticeable. I simply cut and paste some math code snippets from one parameter in a `#functor_diagram` call to another parameter in a different `#functor_diagram` call. The `functor_diagram` function calls `Fletcher`, which in turn calls `Cetz`. Invalidating its cache consistently leads to time-consuming incremental compilation. By repeating this process, the refresh becomes unresponsive, and I begin to notice that it takes more than 30 seconds to compile.

**Comment by Myriad-Dreamin** [comment]
I have found a huge problem when looking into this debug project. lsp server doesn't limit number of threads to run analysis. A typical approach to check is hold your `ctrl` key and move your cursor to a bunch of identifiers, then lsp will start threads to check definition. This will eat up all resources.

**Comment by Myriad-Dreamin** [comment]
![image](https://github.com/user-attachments/assets/9fcf3491-b93c-464b-8cab-7ecd83c9abeb)

There is also an interesting observation: after the emits overwhelming number of definition requests, lsp keeps using hundreds of milliseconds to run cleaning cache command. This means some compilation cache (8GB in my side) cannot be cleaned forevery.

**Comment by Myriad-Dreamin** [comment]
> I have found a huge problem when looking into this debug project. lsp server doesn't limit number of threads to run analysis. A typical approach to check is hold your `ctrl` key and move your cursor to a bunch of identifiers, then lsp will start threads to check definition, which establishes `typst::compile` internally. This will eat up all resources.

I have made a dump but effective implementation. Specifically, I just locked `typst::compile`s to avoid concurrent compilation. I still have no time to make a full implementation.

Hotspot:

![fecdb33f2e3e61a452595c2f87fdac3a](https://github.com/user-attachments/assets/ec2fa63a-96e4-457b-8be9-39d0106442df)

Before:

![image](https://github.com/user-attachments/assets/92d652dc-ad2a-4473-a339-aa4f91373a39)

After:

![image](https://github.com/user-attachments/assets/017287a9-1f65-4d1a-9ed9-25810aab440c)

**Comment by Myriad-Dreamin** [comment]
Could you check it https://github.com/Myriad-Dreamin/tinymist/actions/runs/10398805219? Following the [instructions to install a nightly release.](https://github.com/Myriad-Dreamin/tinymist?tab=readme-ov-file#installing-regularnightly-prebuilds-from-github)

I suspect too many compilations were taking CPU resource so that "imcremental compilation" becomes slower than even "full compilation".

**Comment by Dherse** [comment]
Just as a note: I've had this happen in regular typst a lot with the manual of https://github.com/Dherse/codly

**Comment by Myriad-Dreamin** [comment]
@Dherse what is "regular typst"? Do you mean this is happening in typst-cli as well?

**Comment by Dherse** [comment]
@Myriad-Dreamin yes i meant the cli

**Comment by Myriad-Dreamin** [comment]
The performance about incremental compilation is improved accordingly. Let's open another issue to focus other problem if there is one.
