### ISSUE TITLE
langauge server configuration entries should be children of the top-most entry `tinymist` 

### ISSUE THREAD

**Issue by Ziqi-Yang** [Myriad-Dreamin/tinymist#533]
Note: I'm not talking about initialization options, but settings.

I have read the [tinymist language server configuration doc](https://github.com/Myriad-Dreamin/tinymist/blob/main/editors/neovim/Configuration.md). It has configuration entries like `outputPath` directly on the top-most level, i.e. 
```
outputPath
exportPdf
...
``` 
However, many other language servers like [rust-analyzer](https://rust-analyzer.github.io/manual.html#configuration), [python language server](https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md), [gopls](https://github.com/golang/tools/blob/master/gopls/doc/vim.md#configuration) uses `rust-analyzer`, `pylsp`, `gopls` as the top-most entry of their setting respectively. That's to say:
```
tinymist
├── outputPath
├── exportPdf
...
``` 

Currently, I have to configure Emacs like this to successfully customize Tinymis (though I know I can also specify the initialization option to configure it):
```elisp
  (setq-default eglot-workspace-configuration
                '(:exportPdf "onSave"))
```
Instead of this:
```elisp
(setq-default eglot-workspace-configuration
              '((:pylsp . (:plugins (:ruff (:enabled t))))
                (:tinymist (:exportPdf "onSave"))))
 ```
 You can see the difference. If I want to customize `tinymist`, then I need to discard all configurations for other language servers, since `eglot-workspace-configuration` is directly passed into `tinymist` as a whole (the following log corresponds to the first one configuration style):

```
[2024-08-15T06:14:48Z INFO  tinymist::init] preferred theme: None {"exportPdf": String("onSave")}
[2024-08-15T06:14:48Z INFO  tinymist::server] new settings applied
```

I believe having `tinymist` as the top-most level configuration entry is meaningful - maybe it enables multiple language servers working?

**Comment by Myriad-Dreamin** [comment]
Can emacs put entries under `tinymist` or configure `tinymist` separately? Since, for example, neovim retrieve settings per lsp server.

https://github.com/Myriad-Dreamin/tinymist/blob/68911d91cbaea2e9fb91f33df3d803b5b433ee41/editors/neovim/plugins/tinymist.lua#L28-L29

Btw, you can try `tinymist.exportPdf`, as lsp server requests both `xxx` and `tinymist.xxx` as well.

https://github.com/Myriad-Dreamin/tinymist/blob/68911d91cbaea2e9fb91f33df3d803b5b433ee41/crates/tinymist/src/init.rs#L288-L290

**Comment by Ziqi-Yang** [comment]
> Can emacs put entries under tinymist or configure tinymist separately without changing lsp server?

Emacs have many lsp client implementations, such as `eglot`, `lsp-mode`, `lsp-bridge` and `lspce`, among which `eglot` becomes as the official one since Emacs 29.  
For eglot, it is not possible to pass configuration separately and specifically to a certain langauge server. It will always pass the value of `eglot-workspace-configuration` as a whole into the the language server it launched. I think it does this style is because many other language server does make their name as the top-level entry just like namespace.

---

> Btw, you can try tinymist.exportPdf, as lsp server requests both xxx and tinymist.xxx at same time.

This can work (corresponding to `exportPdf`), but `tinymist`'s configuration pollutes `eglot-workspace-configuration`
```elisp
  (setq-default eglot-workspace-configuration
                '(:pylsp (:plugins (:ruff (:enabled t)))
                         :exportPdf "onSave"))
```
And this is its log:
```
[stderr]  [2024-08-15T12:29:09Z INFO  tinymist::init] preferred theme: None {"exportPdf": String("onSave"), "pylsp": Object {"plugins": Object {"ruff": Object {"enabled": Bool(true)}}}}
[stderr]  [2024-08-15T12:29:09Z INFO  tinymist::server] new settings applied
```

But this cannot: (corresponding to `tinymist.exportPdf`)
```elisp
  (setq-default eglot-workspace-configuration
                '(
                  :pylsp (:plugins (:ruff (:enabled t)))
                  :tinymist (:exportPdf "onSave")))
```
And this is its log:
```
[stderr]  [2024-08-15T12:31:26Z INFO  tinymist::init] preferred theme: None {"pylsp": Object {"plugins": Object {"ruff": Object {"enabled": Bool(true)}}}, "tinymist": Object {"exportPdf": String("onSave")}}
[stderr]  [2024-08-15T12:31:26Z INFO  tinymist::server] new settings applied
```

**Comment by Myriad-Dreamin** [comment]
I'm confused because I don't know whether when we add a `tinymist` section, the neovim users must configure like this:
```lua
  -- add tinymist to lspconfig
  {
    ---@class PluginLspOpts
    opts = {
      ---@type lspconfig.options
      servers = {
        tinymist = {
          settings = {
            tinymist = { exportPdf = "onTyped" } 
          }
        },
      },
    },
  },
```

On the path, `tinymist` occurs twice.

**Comment by Ziqi-Yang** [comment]
gopls also have `gopls` occurs twice (see https://github.com/golang/tools/blob/master/gopls/doc/vim.md#configuration):
```lua
local lspconfig = require("lspconfig")
lspconfig.gopls.setup({
  settings = {
    gopls = {
      analyses = {
        unusedparams = true,
      },
      staticcheck = true,
      gofumpt = true,
    },
  },
})
```
Though I don't think it's mandatory. And there may also be some or many language servers don't use its name as the top-level entry beyond my preliminary investigation.

If you don't like to add an top-level entry/namespace, it's absolutely OK. The reason I propose it is because that setting it in Emacs `eglot-workspace-configuration` seems awkward. However, I can also change the initial launch argument to make it work too. BTW, I'd like to add a instruction file for using `tinymist` in Emacs.

**Comment by Myriad-Dreamin** [comment]
I think of it reasonable to detect whether there is a `tinymist` section returned from client and merged with rest sections, which should have higher priority. It means the following configuration is totally valid:

```lua
 -- add tinymist to lspconfig
  {
    ---@class PluginLspOpts
    opts = {
      ---@type lspconfig.options
      servers = {
        tinymist = {
          settings = {
            tinymist = { exportPdf = "onTyped" } -- priority: high
            'tinymist.exportPdf' = "onTyped" -- priority: middle
            exportPdf = "onTyped" -- priority: low
          }
        },
      },
    },
  },
```

The only thing must be ensured is not to disturb users from other editors.

**Comment by Sinofine** [comment]
Currently, `on_configuration_changed` still directly requires `update_by_map`, thus the procedures taken on #835 is bypassed.
https://github.com/Myriad-Dreamin/tinymist/blob/2257fdc8ceaa0ba8a0a117a736bf92cf83b20f97/crates/tinymist/src/lsp.rs#L132-L146
