### ISSUE TITLE
Invalid display of variable fonts in preview

### ISSUE THREAD

**Issue by TimeTravelPenguin** [Myriad-Dreamin/tinymist#536]
**Describe the bug**
Preview does not display variable fonts correctly.

## As shown in preview:
<a href="https://github.com/user-attachments/assets/d7ba03ca-a8ba-4d0d-b964-3348e6e67cf4"><img src="https://github.com/user-attachments/assets/d7ba03ca-a8ba-4d0d-b964-3348e6e67cf4" width=500/></a>

## As shown in the compiled PDF:
<a href="https://github.com/user-attachments/assets/177f870b-c0a6-4aa0-af3b-0804b64e5a20"><img src="https://github.com/user-attachments/assets/177f870b-c0a6-4aa0-af3b-0804b64e5a20" width=500/></a>

**Package/Software version:**

Using NeoVim

tinymist extension version: `v0.11.1`. Get it by `tinymist --version` in terminal.
```plain
tinymist
Build Timestamp:     2024-08-11T05:30:18.000000000Z
Build Git Describe:  VERGEN_IDEMPOTENT_OUTPUT
Commit SHA:          VERGEN_IDEMPOTENT_OUTPUT
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: aarch64-apple-darwin
Typst Version:       0.11.1
```

**Additional context**
The font I am using can be found [here](https://fonts.google.com/specimen/Nunito)

**Comment by Myriad-Dreamin** [comment]
Could you use the ttf version of this font? typst currently doesn't support variable fonts well (thus may have some unexpected behaviors).

**Comment by TimeTravelPenguin** [comment]
Ah, I see. I looked at the typst documentation but didn't see anything saying not to use it. I suppose I will have to make do until such a time as it becomes better supported.
