### ISSUE TITLE
Outline doesn't nest locals

### ISSUE THREAD

**Issue by memeplex** [Myriad-Dreamin/tinymist#537]
**Describe the bug**

The outline shows everything as a flat list that quickly becomes unwieldy.

```typst
#let fun() = {
  let a = 1
  let clos() = 2
}
```

<img width="85" alt="image" src="https://github.com/user-attachments/assets/5ed6c125-2d31-4f73-a265-a0a7a78d00c0">

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.92.2 (Universal)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.4.0
```

tinymist extension version: `v0.11.0`. Get it by `tinymist --version` in terminal.
```plain
Build Timestamp:     2024-08-11T06:19:46.822520000Z
Build Git Describe:  v0.11.19
Commit SHA:          606486b9fd64d117880578477c0188a136094db1
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: aarch64-apple-darwin
Typst Version:       0.11.1
```

**Comment by Eric-Song-Nop** [comment]
It is clearly a bug/not implemented, I am looking into it
