### ISSUE TITLE
Outline could show Symbols for included files

### ISSUE THREAD

**Issue by daniel-eder** [Myriad-Dreamin/tinymist#541]
**Motivation**

I believe it is a common pattern for larger works to use a "main.typ" file and then include content files. Currently, this makes the outline largely unusable, as each file only shows its local symbols (usually just one section/chapter), and the main file shows nothing.

**Description**

The outline should include symbols for included files. The Preview already supports this fully: It renders included files, but more, it also allows to open an included file from the preview by just clicking any text there.

I believe it is useful expected behaviour to have the outline behave the same way and allow quick navigation to any symbol that will be part of the rendered output document. 

Open question: I am not sure how the outline should work in the included file. By default it would of course just show the symbol in that file (and in files the included file includes), but arguably some way to jump back to main would be desirable.

**Comment by memeplex** [comment]
[Last week I requested](https://github.com/Myriad-Dreamin/tinymist/issues/496) the ability to extend the outline with custom regexs, because of a related problem: in a slideshow logical sections and subsections are wrapped inside `#slide`-like commands and the outline remains empty although it could show more useful information.

It was suggested there that I should enable the:

> exported document outline in "ActivityBar > Tinymist > Outline"

which

> is behind on a feature flag tinymist.preview.showInActivityBar.

I believe this should be the way to go instead of special-casing the outline once and again.

But there are a couple of rough edges that I think should be fixed before:

1. It's quite hidden behind a seemingly unrelated and experimental setting.
2. It's tied to that setting, which also shows thumbnails that may be a bit too expensive if you only want to enable the outline.

Regarding 2, perhaps it's ok that both features are enabled at once, if you think of them as TOC+thumbnails in your favourite PDF reader.

**Comment by Eric-Song-Nop** [comment]
I don't think it is a common practice to show included symbols in the outline, as regarding language serve protocol, the outline simply shows the document symbols, I believe it is shared be other tools to find and jump to document symbols.

**Comment by memeplex** [comment]
> I don't think it is a common practice to show included symbols in the outline

I agree but Typst is two-folded in this regard, as a programming language and as a markup language.

One outline shows the main features of your source document, including function declarations and sections. These are somewhat static, directly taken from the surface of the document, so sections are obscured by the programming part: includes, slide-functions and whatnot.

The output outline reflects the structure of the document as a, well, document, the same that you would get after opening the exported pdf in e.g. Preview.

The extension is already providing both.

**Comment by Eric-Song-Nop** [comment]
I totally agree with the importance of this, but outline is something implemented by language clients, which is editor, what they do is just querying document symbols, if workspace symbols are feeded, it might cause problems with range/jumping for different implementations.

**Comment by daniel-eder** [comment]
> [Last week I requested](https://github.com/Myriad-Dreamin/tinymist/issues/496) the ability to extend the outline with custom regexs, because of a related problem: in a slideshow logical sections and subsections are wrapped inside `#slide`-like commands and the outline remains empty although it could show more useful information.
> 
> It was suggested there that I should enable the:
> 
> > exported document outline in "ActivityBar > Tinymist > Outline"
> 
> which
> 
> > is behind on a feature flag tinymist.preview.showInActivityBar.
> 
> I believe this should be the way to go instead of special-casing the outline once and again.
> 
> But there are a couple of rough edges that I think should be fixed before:
> 
> 1. It's quite hidden behind a seemingly unrelated and experimental setting.
> 2. It's tied to that setting, which also shows thumbnails that may be a bit too expensive if you only want to enable the outline.
> 
> Regarding 2, perhaps it's ok that both features are enabled at once, if you think of them as TOC+thumbnails in your favourite PDF reader.

Thank you so much!
I agree with you entirely, this does fit the feature request, but it also should be made more accessible, and most likely be a separate setting.
