### ISSUE TITLE
on enter block equations for math mode

### ISSUE THREAD

**Issue by Mc-Zen** [Myriad-Dreamin/tinymist#548]
Thanks for this awesome LSP! I love it. 

I want to suggest that hitting `Enter` after inserting a `$` produces
```
$
  |    ← cursor
$
```
just as with `{`, `(`, or `[`. This would greatly improve the workflow of writing display style equations. As specific usecase I have longer and more complex equations in mind that require multiple lines. Or just to improve source code readability by setting block equations visually apart from the text. 

This feature could also be an option that can be turned on or off.

**Comment by Myriad-Dreamin** [comment]
looks nice, it can also be simply implemented, but I wonder whether typstyle will remove the empty indents. This might introduce some inharmony.

**Comment by Mc-Zen** [comment]
Do you mean whether it will remove them immediately? Is the formatter (if activated) called automatically?

**Comment by Myriad-Dreamin** [comment]
> Do you mean whether it will remove them immediately? Is the formatter (if activated) called automatically?

Yes.

**Comment by Enter-tainer** [comment]
It is actually not formatter's fault. Typst's parser thinks that `$  $` is inline equation for some reason. see linked issue above https://github.com/typst/typst/issues/4791

**Comment by Mc-Zen** [comment]
Nice!

**Comment by Mc-Zen** [comment]
Amazing, thank you!
