### ISSUE TITLE
Support ``--timings`` extra argument

### ISSUE THREAD

**Issue by spidersouris** [Myriad-Dreamin/tinymist#552]
**Motivation**

Currently, the ``--timings`` ([Typst source](https://github.com/typst/typst/blob/a30b681251ef684b4bcfdc43787ad058b5e600f6/crates/typst-cli/src/args.rs#L120)) extra argument is unsupported, triggering a "failed to parse typstExtraArgs" error. Supporting this extra arg could be useful to analyze compilation time and work on optimizations for templates or specific files.

**Description**

N/A

**Examples/Questions**

N/A

**Comment by Myriad-Dreamin** [comment]
https://github.com/Myriad-Dreamin/tinymist/pull/166

![image](https://github.com/user-attachments/assets/5bb97f92-9d63-4556-b896-a36b05e8cf99)

**Comment by spidersouris** [comment]
Ah, missed that! Thank you.
