### ISSUE TITLE
Inline code followed by double quote causes incorrect syntax highlighting

### ISSUE THREAD

**Issue by MDLC01** [Myriad-Dreamin/tinymist#556]
**Describe the bug**

Tinymist highlights the following piece of code incorrectly, coloring `"foo\n"` as if it were a code-mode string and `bar` as a code-mode identifier.

```typ
#ident"foo
"bar
```

**Package/Software version:**

tinymist extension version: `v0.11.1`. Get it by `tinymist --version` in terminal.
```plain
tinymist 
Build Timestamp:     2024-05-18T05:16:29.224809100Z
Build Git Describe:  v0.11.9-dirty
Commit SHA:          49c665de6631bc6f989f8289650efcbf116359ab
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-pc-windows-msvc
Typst Version:       0.11.1
```

**Comment by Myriad-Dreamin** [comment]
As a workaround: 
```typ
#let a = 1;
#a;""
```
