### ISSUE TITLE
Automatic preview page fit width

### ISSUE THREAD

**Issue by TimeTravelPenguin** [Myriad-Dreamin/tinymist#576]
**Motivation**

I often work on a laptop, and so I often need to zoom in on the preview to see (I also have poor eyesight). Being able to automatically zoom to the page margin would help because using touchpad gestures is a pain.

**Description**

I am a user of TexStudio, which is where I got this idea from. Their previewer has buttons to zoom to page width and zoom to margin fit. Having a hotkey or something to toggle this zoom option would make it very helpful. One helpful aspect is also locking the horizontal scroll so that touchpad users can scroll while focused on the page body without accidentally scrolling the page off-centre.

**Examples/Questions**

See the following screenshot showing how the preview (on the right) is zoomed to show the page body.

![CleanShot 2024-08-28 at 12 55 00@2x](https://github.com/user-attachments/assets/c3a0945c-92b9-4d84-8d9f-7b3d8153a17b)

**Comment by Myriad-Dreamin** [comment]
You could check it for customizing looking in template for previewing: https://github.com/Myriad-Dreamin/tinymist/issues/428

Known issue: this will also affect pdf export in lsp.

**Comment by Myriad-Dreamin** [comment]
documentation: https://myriad-dreamin.github.io/tinymist/feature/preview.html#label-sys.inputs

**Comment by TimeTravelPenguin** [comment]
> You could check it for customizing looking in template for previewing: #428

Unfortunately, I don't think this can work for me. My custom template has some math the is determined on the margins (And I think some other things? I can't remember off the top of my head).

This is especially the case when I am making specific adjustments to layouts and such for my uni assessments, where I am attempting to fit equations or code onto a specific page without breaking.

**Comment by Myriad-Dreamin** [comment]
I don't quite understand, but we are probably not going to change previewer to clip margin, since nothing other than your template know your margin settings well.
