### ISSUE TITLE
Label autofill pop-up list missing while typing arguments in some user-defined functions

### ISSUE THREAD

**Issue by miles-1** [Myriad-Dreamin/tinymist#579]
**Describe the bug**
One great feature of Tinymist is the autofill options list that appears when typing a label with `<>`, including citation labels imported with the `bibliography` function.  However, within some (not all) user-defined functions, citation labels do not appear as options in that pop-up list while typing. In fact, the example in the gif below shows that the exact same function will behave differently if named differently. The gif shows that `<Abrams_1997a>` appears when you begin to type it in the `cite_prose` function, but not in the `cite_prose_different_name` function. It seems that the order in which these functions are defined or used have no effect on this behavior. I have experimented with different names of functions and cannot find a pattern in what causes the pop-up list to include citation labels or not.

![example](https://github.com/user-attachments/assets/fc6f6f57-01c3-49a6-9a4c-7eb0e56ae131)

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.92.2 (Universal)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 23.5.0
```

tinymist extension version: `v0.11.20`.

**Logs:**
N/A

**Additional context**
N/A

**Comment by Myriad-Dreamin** [comment]
if you let it compiled again, label completion will work again. This is because labels are collected by compilation. If that works for you, what you found should not be a bug but a feature.

This could be improved carefully tho.

**Comment by Myriad-Dreamin** [comment]
I have started to look into it, but I may move slowly as there might be some really subtle bugs inside.

Observation 1, in your image it actually shows label completions at first key stroking, but after that it goes away quickly:

![image](https://github.com/user-attachments/assets/fba56e3c-c0bc-498d-acc5-780d53583461)

Observation 2, my type checker extracted the signature of `cite_prose{,_different_name}` but label completion still fails:

https://github.com/Myriad-Dreamin/tinymist/blob/bc289861eb789444a71142b65146bdcb90a0d01b/crates/tinymist-query/src/fixtures/type_check/snaps/test%40bug_cite_func_infer.typ.snap#L3-L7

so I judge that the bug may come from function type signatures are incorrectly cached by *completion* API. I need more time to survey it.

**Comment by Myriad-Dreamin** [comment]
The root cause is that laurenz was checking a function can cite bib items by a small name window:

https://github.com/Myriad-Dreamin/tinymist/blob/58fea291ad8ffe942b51c52bd9225a6d344a01a5/crates/tinymist-query/src/upstream/complete.rs#L1114
