### ISSUE TITLE
Semantic highlighting conflicts with syntax highlighting on raw blocks

### ISSUE THREAD

**Issue by AcrossForest** [Myriad-Dreamin/tinymist#585]
**Motivation**

To enhance the experience when writing code examples.

**Description**

Implement syntax highlighting or language server integration when writing code snippets, leveraging existing capabilities of Visual Studio Code.

**Examples/Questions**

Consider the following examples of Markdown and LaTeX:

Markdown:
![image](https://github.com/user-attachments/assets/cd8dbb3f-d327-41e3-8303-0276f7567237)

Latex:
![image](https://github.com/user-attachments/assets/326eeaec-eb06-41e2-84b0-1f5677dbfb7e)

However, in Typst, we observe:

![image](https://github.com/user-attachments/assets/d0f6db26-36d1-4904-ab59-36bbfaa25ac8)

**Comment by Enter-tainer** [comment]
I observed an interesting effect when reproducing this issue. When i finish a line, the code *is* correctly highlighted. However it quickly become monochrome. Maybe it is typst's semantic highlight overriding vscode's textmate syntax highlighting?

**Comment by Myriad-Dreamin** [comment]
It works on my end. So perhaps your theme has some special rules on `meta.embed` scopes but I'm not sure.

![image](https://github.com/user-attachments/assets/a04d531c-96c3-48c3-b642-e9508d0c0a1b)

**Comment by AcrossForest** [comment]
@Myriad-Dreamin 
Thanks for your feedback.  I have some extra information:
1. I disabled all extensions in vscode except the Tinymist Typst. And the problem still exists.
2. I noticed I have exactly the same effect @Myriad-Dreamin mentioned: I initially have some colored highlight, and then it becomes monochrome in about 0.3s or so.
3. I obtained the same figure as your feedback, which might be helpful for you.
![image](https://github.com/user-attachments/assets/3864bb55-229a-42c2-a3aa-4fd2fa1edb39)

**Comment by Enter-tainer** [comment]
btw i'm using modern light theme in vscode(which is one of the default light theme comes with vscode)

**Comment by Myriad-Dreamin** [comment]
What's the result of using 'Typst (Code Mode)'? This is a variant of syntax that doesn't have semantic highlighting.

![image](https://github.com/user-attachments/assets/84b57212-1d2d-410b-a2a7-08bfdd9b7331)

**Comment by Enter-tainer** [comment]
<img width="941" alt="image" src="https://github.com/user-attachments/assets/1ecb3e2e-16be-4804-bf6f-859b2d2644e7">

Typst (Code Mode) is functional on my side

**Comment by AcrossForest** [comment]
Typst (Code Mode) works for me as well. But there is nothing else rendered in this mode.

**Comment by Myriad-Dreamin** [comment]
Please don't use code mode or markdown injection as they are use some special scenario. This only proves the root cause is semantic highlighting conflicting with syntax highlighting.
