### ISSUE TITLE
Pass in filename through environment variable

### ISSUE THREAD

**Issue by DUOLabs333** [Myriad-Dreamin/tinymist#587]
**Motivation**

I'm coming from LaTeX, where I can use `\jobname` to get the filename so I can do some operations on it. Typst doesn't have this, so I would need to pass this in when compiling.

**Description**
It could probably take the form of an option `passinFileName`. If the option is true, pass in the full absolute file name as `TINYMIST_FILE_PATH`. Alternatively, you can split the path into two variables --- one for the base name, and one for the parent directory.

**Comment by Myriad-Dreamin** [comment]
it (passing filename via sys.inputs) is already well discussed and considered as not conforming typst's philosophy. Thus to get filename in typst scripting, we should find a correct way first.

**Comment by DUOLabs333** [comment]
Oh, I saw the related issue (https://github.com/typst/typst/issues/295), and thought that since it was closed, support was added. Reading it again, it seems that issue was simply put off indefinitely.

**Comment by DUOLabs333** [comment]
I was investigating this problem again, and I noticed that typst already has support for passing arguments through the cli (https://github.com/typst/typst/pull/2894) --- so we can just do `--input TINYMIST_FILEPATH={current_file}`.

**Comment by DUOLabs333** [comment]
We can pass in custom arguments with `typstExtraArgs`, but I'm not sure how to make it so that it's always the current file that would be passed in; ie, would something like `typstExtraArgs=['--input', 'TINYMIST_FILEPATH=$dir']` work?

**Comment by Myriad-Dreamin** [comment]
> We can pass in custom arguments with `typstExtraArgs`, but I'm not sure how to make it so that it's always the current file that would be passed in; ie, would something like `typstExtraArgs=['--input', 'TINYMIST_FILEPATH=$file']` work?

this shouldn't work as we don't interpret variables in typstExtraArgs. And note this is exactly what i said "passing filename via sys.inputs", which is considered not a right typst style (usage).
