### ISSUE TITLE
Add a setting option to not follow into different files/imports.

### ISSUE THREAD

**Issue by Rickyneer** [Myriad-Dreamin/tinymist#591]
Thank you for the extension!

**Motivation**

Currently, whenever you click somewhere in the preview, it will try to navigate to where that is defined, let it be any shape or text. This is a really handy feature and nice to have. However, when using (some) templates, it links to the root definition which is in the imported template. This is okay and an intended feature, however it would be nice to have an option to limit this to just your current file, or files that aren't imported.

**Description**
Addition to the click to navigate to feature, where upon clicking, it will check whether the origin is in the current file or is from an imported file and whether the settings was enabled or not, navigate to it in the editor.

**Examples/Questions**

- When clicking on text that is generated by an imported file, with the setting to not follow origins outside of current or imported files, do not navigate to the origin.
- When clicking on text that is generated by an imported file, with the setting to follow origins outside of current or imported files, do navigate to the origin.
- Will this cause breaking changes to existing workflows? Yes, hence why I'd like to propose this as an addition that is not the default setting.
- Would imported files also rule out files created yourself? Yes, I suggest to be able to have an allowlist/blocklist where you can configure paths.
- When you click on the text in the .typ file, you navigate to the preview page's page when activated, will that possibly break thsi feature? Yes, when for example text is clicked that is from a blocklist specified file, though this can be solved with a simple conditional statement.

**Comment by Rickyneer** [comment]
> In short, source location looking up is an internal feature of typst so we as a downstream cannot add more features like that requested in this FR. This is also known to be a hard feature from existing discussion. duplicated #581

Say this will be a feature implemented by typst in the feature through CLI arguments, is it useful to then reopen this issue?

**Comment by Myriad-Dreamin** [comment]
> Say this will be a feature implemented by typst in the feature through CLI arguments, is it useful to then reopen this issue?

First, it is a duplicated request with #581. Second, we should discuss concrete way of improvment in typst/typst.
