### ISSUE TITLE
one page instead of continuous scroll

### ISSUE THREAD

**Issue by rveltz** [Myriad-Dreamin/tinymist#609]
I try to use typst for presentations. It works great combined with tinymist preview in the browser. My only issue is that there seems to be no way for one page viewing instead of continuous scroll. Am I right?

**Comment by rveltz** [comment]
Actually: https://github.com/Enter-tainer/typst-preview/pull/177

**Comment by Myriad-Dreamin** [comment]
You've found it. You could use the slide mode, entering it by commands or click the code lenses at the top view of your each document file.

**Comment by rveltz** [comment]
yes ! thank you
