### ISSUE TITLE
 Preview icon disappears when clicking outside the document

### ISSUE THREAD

**Issue by supersurviveur** [Myriad-Dreamin/tinymist#615]
This issue came from [Typst Preview#262](https://github.com/Enter-tainer/typst-preview/issues/262)

**Describe the bug**
When I click outside the typst document (but keeping it open), the preview icon in the top right-hand corner disappears.

https://github.com/Enter-tainer/typst-preview/assets/54775010/a8a30463-3d27-4fc6-b3a7-c253a08b2947

**To Reproduce**
+ Open a typst document
+ Click outside the document (in the terminal or in the directory tree)

**Expected behavior**
The preview icon should remain visible as long as the document is open, even if the user clicks outside the document.

**Package/Software version:**

```plain
tinymist
Build Timestamp:     2024-08-26T16:22:10.986712173Z
Build Git Describe:  v0.11.20
Commit SHA:          1f9a42c2e863f6b1fe8624da796e47adf44a9a83
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-unknown-linux-gnu
Typst Version:       0.11.1
```

**Comment by Myriad-Dreamin** [comment]
The current status is not pleasant but already expected. I tried to investigate that. The main reason behind is that the language server doesn't know your UI status, so all that associated with UI behaviors will be hard to implement.

**Comment by Myriad-Dreamin** [comment]
FWIW, the builtin markdown support seems to have solved it, it is worth to checking how they did it.
