### ISSUE TITLE
Failed to Download v0.11.28 via Mason (Neovim)

### ISSUE THREAD

**Issue by cskeeters** [Myriad-Dreamin/tinymist#637]
**The bug**
When I went to install the updates LSP in Neovim using Mason, an error was shown in the Mason UI.

```
  Failed
    ◍ tinymist
      ▼ Displaying full log
        Downloading file "https://github.com/myriad-dreamin/tinymist/releases/download/v0.11.28/tinymist-darwin-arm64"…
        spawn: wget failed with exit code 8 and signal 0. 
        Failed to download file "https://github.com/myriad-dreamin/tinymist/releases/download/v0.11.28/tinymist-darwin-arm64".
```

It seems the correct link for v0.11.28 has a `-4` appended to it.

```
https://github.com/Myriad-Dreamin/tinymist/releases/download/v0.11.28-4/tinymist-darwin-arm64
```
**Versions**

Neovim v0.10.2 with Lazy the latest version of these managed plugins:
```
  "mason-lspconfig.nvim": { "branch": "main", "commit": "25c11854aa25558ee6c03432edfa0df0217324be" },
  "mason.nvim": { "branch": "main", "commit": "e2f7f9044ec30067bc11800a9e266664b88cda22" },
  "nvim-lspconfig": { "branch": "master", "commit": "3805bb215ca2eb3e047c947fc4bf2434ca473ff6" },
```

**Caveats**

I'm not sure where to report this bug because I'm not sure if the problem is with lspconfig/mason for not knowing there should be a `-4` or with tinymist for having the `-4`.

**Comment by tristan957** [comment]
Looks like the tag name is formatted differently than usual.

![image](https://github.com/user-attachments/assets/637808d5-baa5-49e7-874d-daae49db121c)

**Comment by ruimp** [comment]
Any advice on how to work around this problem while Mason install is not working? Thanks!

**Comment by kamransoomro84** [comment]
I have the same issue.

**Comment by Myriad-Dreamin** [comment]
Is 0.11.32 working now? It is just a republish of 0.11.28 and doesn't contain new feature.

**Comment by cskeeters** [comment]
Worked for me!
