### ISSUE TITLE
Request: Documentation for configuring tinymist in the Zed editor

### ISSUE THREAD

**Issue by Gaspartcho** [Myriad-Dreamin/tinymist#656]
Currently, the only documentation I can find about configuring this LSP in the Zed editor is [this page](https://myriad-dreamin.github.io/tinymist/frontend/zed.html), which only redirects to the extension's [homepage](https://github.com/WeetHet/typst.zed), which itself does not contains any documentation to configure tinymist in Zed.

I tried to create a basics configuration like this:

```json 
"lsp": {
  "tinymist": {
    "initialization_options": {
      "exportPdf": "onSave"
    }
  }
}
```

but it did not work, and even if I tried to change it in many different ways, it still did not work.

Would it be possible to create the (much needed) documentation for this front-end?

**Comment by Myriad-Dreamin** [comment]
I don't use zed, so I personally cannot help it.

**Comment by mattfbacon** [comment]
The typst.zed repository is a Zed extension which you need to install in your editor.

**Comment by Myriad-Dreamin** [comment]
closed by https://github.com/WeetHet/typst.zed/pull/9
