### ISSUE TITLE
Option to hide "Profile | Preview ..." on editor panel

### ISSUE THREAD

**Issue by lukejanicke** [Myriad-Dreamin/tinymist#661]
**Motivation**

Features that add UI elements should have toggle off/hide options in settings.

**Description**

The following is shown at the top of the editor panel in VS Code.

`Profile | Preview ... | Preview in ... | Export PDF | Export as ...`

It looks/feels cramped. I would like to toggle this off, as the standard VS Code preview button and keyboard shortcut are sufficient, and the PDF can be automatically generated. The UI elements are not necessary, and are  little visually distracting.

See screen grab below.

**Examples/Questions**

- Add setting **Tinymist: Toggle Preview and PDF actions in editor window**

<img width="577" alt="Screenshot 2024-10-11 at 17 14 54" src="https://github.com/user-attachments/assets/36276a7e-810c-455e-98d0-d4a1ceb726fe">

**Comment by Myriad-Dreamin** [comment]
You can disable them by:

```json
  "[typst]": {
    "editor.codeLens": false
  }
```

**Comment by lukejanicke** [comment]
Thanks! That'll do nicely.
