### ISSUE TITLE
Add definition docs (when hovering/autocompleting) for field-like elements (e.g., `math.equation`, `table.cell` etc.)

### ISSUE THREAD

**Issue by Andrew15-5** [Myriad-Dreamin/tinymist#663]
**Motivation**

The more elements supporting the definition docs, the better the UX/DX.

**Description**

All element functions have definition docs on hover, but not the `math.equation`. https://typst.app/docs/reference/math/equation/#parameters should be added to the top of the docs (or fully replace the current docs).

```typ
#set math.equation()
```

The same goes to things like `table.cell`, `table.hline` etc.

**Examples/Questions**

Here is what comes up when completing the `math.equation` or hovering over it:

![image](https://github.com/user-attachments/assets/45ff3af5-1b37-4b84-b3bb-1bf9280cd847)

**Comment by Myriad-Dreamin** [comment]
Isn't the screenshot the docs of `math.equation`?

**Comment by Myriad-Dreamin** [comment]
I see. The docs is shown during completion.

Btw, it is not a regression, we still don't support to hover on fields: `x.y`.

**Comment by Andrew15-5** [comment]
> The docs is shown during completion.

The same docs are shown during completion and hover.

> Btw, it is not a bug or regression, we still don't support to hover on fields, like `y` in `x.y`.

Oh, that explains this. Do we have an issue for this? Or maybe I can edit mine.

**Comment by Myriad-Dreamin** [comment]
> Do we have an issue for this? Or maybe I can edit mine.

We don't have one. You can edit the issue to be a feature request.

**Comment by Andrew15-5** [comment]
Then I guess you should also throw in the enhancement label.

I also tried importing the function and using it directly:

![image](https://github.com/user-attachments/assets/faa64e83-85b0-4de9-9fae-2dda975f478c)

But hovering on parenthesis doesn't do anything, and hovering on function name gives the same docs as before without any definition. This means that it's not that the `x.y` isn't supported, but instead things that are _initially defined_ (or accessible) as `x.y` are not supported. Because I tried using `y` after importing `x: y` and it still didn't work.
