### ISSUE TITLE
Tinymist not for vs code

### ISSUE THREAD

**Issue by WinstonMDP** [Myriad-Dreamin/tinymist#676]
I use helix and zathura. Can tinymist follow a cursor in helix and zathura? And can it preview an exactly currently opened document?

**Comment by Myriad-Dreamin** [comment]
> Can tinymist follow a cursor in helix and zathura?

It cannot response from and to PDF viewers.

> And can it preview an exactly currently opened document?

In helix, it is hard, because helix doesn't support to call LSP commands with arguments, while the preview command requires a path argument.

**Comment by WinstonMDP** [comment]
Thanks
