### ISSUE TITLE
Autocompleting `inset` field from `in` causes `ininset` to be inserted

### ISSUE THREAD

**Issue by Andrew15-5** [Myriad-Dreamin/tinymist#709]
**Describe the bug**

Write:

```typ
#set block(in)
```

Then trigger the completion dropdown menu and select `inset` field. Upon autocompletion, the following is inserted:

```typ
#set block(ininset: )
```

This does not happen with any of the other 4 variants of autocompletion. My guess is that it has to do with the `in` keyword.

**Package/Software version:**

tinymist version:
```plain
Build Timestamp:     2024-10-10T10:20:38.565077580Z
Build Git Describe:  v0.11.33-3
Commit SHA:          57008d82a8f6ffcc4285940fc7e0a409da9a7c43
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-unknown-linux-gnu
Typst Version:       0.12.0-rc1
Typst Source:        git+https://github.com/paran3xus/typst.git?tag=tinymist-typst-0.12-rc1#f9556de71da9cd6a24a4239c8cb3ad57e802e882
```

**Logs:**

**Additional context**

**Comment by Myriad-Dreamin** [comment]
I can reproduce it.

**Comment by Andrew15-5** [comment]
Hmm, it does happen in Neovim v0.10.0. I didn't expect it to be different in different editors.

**Comment by Myriad-Dreamin** [comment]
> Hmm, it does happen in Neovim v0.10.0. I didn't expect it to be different in different editors.

Did you misread the message?

**Comment by Andrew15-5** [comment]
What do you mean? Did I miswrite my message, or did I misread your message? Which editor did you use?

**Comment by Myriad-Dreamin** [comment]
I mean that I can reproduce in vscode that when explicit calling to completion, the language server doesn't view keywords as identifiers correctly.

**Comment by Andrew15-5** [comment]
Oh! Oh! Yes! I did misread your message several times in a row! Now I get it.
