### ISSUE TITLE
A question about disabled LTO

### ISSUE THREAD

**Issue by zamazan4ik** [Myriad-Dreamin/tinymist#715]
Hi!

Excuse me please if it's not the right place to ask such questions - didn't find a better place for doing this.

I [found](https://github.com/Myriad-Dreamin/tinymist/pull/84) that LTO was disabled for the project but didn't find the reason for disabling it. Could you please give a bit more details about the change?

I guessed that LTO brought some build issues but I tested the build with LTO locally - it works fine. Another guess - this is due to the increased build time. In this case, we probably can move enabled LTO to a dedicated profile (like already existing `gh-release` or a new `[profile.dist]` or anything similar) or consider enabling ThinLTO instead since it harms build times less than Fat LTO.

Thank you in advance!

**Comment by Myriad-Dreamin** [comment]
This adds up CI time to half of hours and doesn't give visual boost of performance. Since we have disabled it for months, we can check it again. The lto flags could be added to the default release profile to help people who install tinymist via cargo.

**Comment by Myriad-Dreamin** [comment]
Btw, it would be interesting to explore and compare which one profile gives best performance while we haven't tuned it yet.

**Comment by Myriad-Dreamin** [comment]
Since this issue is merely a question rather than a feature request, I'll close it. Further steps could be made:
- Open a PR that contains profile changes about LTO with benchmark description.
- Open an issue that contains other suggestion to tuning tinymist's performance.

**Comment by zamazan4ik** [comment]
@Myriad-Dreamin am I right that you are interested only in performance-related optimization, without the binary size? I am asking it since comparing before and after binary sizes will be an easy task - I can definitely do it. However, if you need performance benchmarks too, it will require additional efforts to implement.

**Comment by Myriad-Dreamin** [comment]
> am I right that you are interested only in performance-related optimization, without the binary size?

@zamazan4ik Not absolutely. We usually don't quite care about small size changes among released versions, but definitely have concern on optimizing the size of binary. About tracking the binary size, you can check the artifacts on GitHub Actions. The (compressed) size has been raising from 15MB to 20MB since recent half of the year. I personally still feel okay on current state.

**Comment by zamazan4ik** [comment]
Before creating a PR, I wanted to perform some benchmarks on my system (Fedora 41, Rustc 1.82, AMD Ryzen 5900x) with `tinymist` on the commit `4437b3bffb5f01f06bd64e4e424480ba72a88619` from the `main` branch. Here are the results.

Release (`release` profile):
Build time: 2m 6s
Binary size:
 - tinymist: 51 Mib
 - typlite: 34 Mib

Fat LTO (`release` profile + `lto = true`):
Build time: 3m 59s
Binary size:
 - tinymist: 46 Mib
 - typlite: 32 Mib

Thin LTO (`release` profile + `lto = thin`)
Build time: 2m 22s
Binary size:
 - tinymist: 53 Mib
 - typlite: 35 Mib
 
Didn't perform any performance comparisons between 3 versions. If you are okay with such a build time overhead with Fat LTO, I will create a PR to enable it. If you are okay with that but not for a regular Release profile, we can move it to some dedicated profile that is triggered only during releases (to save some CI time) like `gh-release`. If you are not okay with the overhead in any option, I will leave things as is ;)
