### ISSUE TITLE
[Label] The Label of the plugin in VSCode shows labels that are not in the current document

### ISSUE THREAD

**Issue by kands-code** [Myriad-Dreamin/tinymist#716]
**Describe the bug**

Label in VSCode does not show the label as it appears in the current document.

The labels are labels from other documents in the same folder, my documents are single files and not a typst project.

**Package/Software version:**

tinymist extension version: `v0.12.0`. Get it by `tinymist --version` in terminal.

```plain
tinymist 
Build Timestamp:     2024-10-19T17:10:46.837035115Z
Build Git Describe:  v0.12.0
Commit SHA:          4437b3bffb5f01f06bd64e4e424480ba72a88619
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-unknown-linux-gnu
Typst Version:       0.12.0
Typst Source:        git+https://github.com/Myriad-Dreamin/typst.git?tag=tinymist-v0.12.0#58426a90a7ef721738a01be09793d33e55eb75a9

> typst --version
typst 0.12.0 (737895d7)
```

![image](https://github.com/user-attachments/assets/53ec5938-475b-41a8-a9e2-4c7cf3a8f3bb)

**Comment by Myriad-Dreamin** [comment]
This works as expected, because the full name of the label view is "show labels in current workspace". We can make richer feature tho. Since this is not a valid feature request, I'll close it as completed. Feel free to open a new issue containing sensible feature request about the label view.
