### ISSUE TITLE
Small mistake of Chinese quotation mark

### ISSUE THREAD

**Issue by VicolandLafro** [Myriad-Dreamin/tinymist#723]
When using Chinese input, the first shift+' is shown as ![image](https://github.com/user-attachments/assets/524e9324-452d-45f0-bf55-ae7990919bd8). That's OK. But when typing the second, it is only a right mark like ![image](https://github.com/user-attachments/assets/5b10935f-8ef5-4539-b330-55d2dcd32c9a). That's bad.
I prefer either closing every pair of quotation marks, or never auto-closing and just show according to if there is a left mark.

Also, I tried and made sure that it only happened in typst on VS Code. On any explorer my Chinese input method was OK, and when using C++ or python on VS Code, it worked well, too.

(Changing settings is not helpful for this mistake. )

tinymist extension version: v0.12.0

**Comment by Myriad-Dreamin** [comment]
This is a feature (bug) of vscode how it autocompletes chinese brackets. Note: English brackets works fine.
