### ISSUE TITLE
Cursor is invisible after opening preview

### ISSUE THREAD

**Issue by kravlost** [Myriad-Dreamin/tinymist#729]
If I open the preview to the right using Ctrl-K, V, the cursor changes to white in both the preview and source views, which makes it invisible against a white background.

VS code:

Version: 1.94.2 (user setup)

tinymist extension version: `v0.12.0`.

**Comment by Myriad-Dreamin** [comment]
Could you elaborate it? It sounds like not an issue of tinymist.

**Comment by kravlost** [comment]
> Could you elaborate it? It sounds like not an issue of tinymist.

If I have a Markdown file open, and open the preview to the side, the cursor/caret stays black and I can see it clearly on both sides. If I do the same with a Typst file, the cursor/caret turns white and cannot be seen on either side.

**Comment by kravlost** [comment]
Never mind, I'm using Markdown and pandoc to compile through typst so I don't need this extension.
