### ISSUE TITLE
Emojis not shown in VS Code preview in last version

### ISSUE THREAD

**Issue by pammacdotnet** [Myriad-Dreamin/tinymist#731]
Emojis are simply not rendered in the last VS Code insiders version: 
Version: 1.95.0-insider
Commit: 39fd376a04ae461e1abb4212d6395d7a56959198
Date: 2024-10-24T05:04:31.844Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0

**Comment by pammacdotnet** [comment]
This was previously possible by just typing the corresponding emoji. With version 0.12 it has stopped working. 
![WhatsApp Image 2024-09-20 at 17 04 49](https://github.com/user-attachments/assets/da72b714-ff4c-47d9-b8c7-2d4b821d2cbe)

**Comment by Myriad-Dreamin** [comment]
The https://github.com/typst/typst/pull/5169 broke the glyph renderers. Turning `Abs::raw` to `Abs::pt` in renderers will fix this bug.
