### ISSUE TITLE
@preview/g-exam:3.2 documentation not displayed

### ISSUE THREAD

**Issue by andres-gimenez** [Myriad-Dreamin/tinymist#738]
**Describe the bug**
I'm developing the @preview/g-exam:3.2 library and I don't see the documentation in vscode with tinymist. I don't know why it is. Any suggestions? Is it tinymist's problem or should something change?

**@preview/g-exam:3.2**

```plain
tinymist:   `v0.12.0`
Build Timestamp:     2024-10-27
Build Git Describe:  v0.12.0
Typst Version:       0.12.0
```

**Comment by Myriad-Dreamin** [comment]
Currently the documentation feature is in very early stage. We currently follows https://github.com/typst-community/guidelines/pull/8 to parse docs.

The plan is to improve docs and completion experience package by package first. I'm now working to make better documentation for `@preview/touying`. Once we finish to check few packages, we will make some manual to clarity how to make and gain better docs or completion for packages. If possible, we may also submit feedback to typst/typst upstream.

---

After checking `@preview/touying`, I will also check `@preview/g-exam` for you.

**Comment by Myriad-Dreamin** [comment]
> in vscode

If you mean you didn't see the package in the "PACKAGE" view, their is a know issue, #717.
