### ISSUE TITLE
Tinymist causes semantic token error in neovim when typing Chinese

### ISSUE THREAD

**Issue by fit-sizhe** [Myriad-Dreamin/tinymist#761]
**Describe the bug**
Tinymist causes neovim error when typing Chinese. The error message is shown below
![image](https://github.com/user-attachments/assets/6c24c0c9-e859-4d49-afc7-062a6be872e4)

**Package/Software version:**
tinymist extension version: `v0.12.0`, installed through "mason.nvim"

**My tinymist config**
```lua
      lspconfig.tinymist.setup({
        single_file_support = true,
        root_dir = function()
          return vim.fn.getcwd()
        end,
        settings = {
          semanticTokens = "disable",
          formatterMode = "typstyle",
        },
      })
```
The error appears whenever I type Chinese character,and disabling semanticTokens does not make the error go away.

**Comment by Enter-tainer** [comment]
https://github.com/neovim/neovim/issues/30675

**Comment by fit-sizhe** [comment]
@Enter-tainer adding "offset_encoding" does make the semantic token error go away, but I keep getting "unexpected x","unclosed string" errors everywhere from tinymist. and the syntax hightlighting is off once there were Chinese characters.

**Comment by Enter-tainer** [comment]
hi @fit-sizhe , please open a new issue for this. thanks!

**Comment by fit-sizhe** [comment]
related issue: #766
