### ISSUE TITLE
32-bit arm architectures failing test_ty_size

### ISSUE THREAD

**Issue by selfisekai** [Myriad-Dreamin/tinymist#762]
**Describe the bug**

this test fails on Alpine Linux armhf (`armv6-alpine-linux-musleabihf`, ~`arm-unknown-linux-musleabihf`) and armv7 (`armv7-alpine-linux-musleabihf`, ~`armv7-unknown-linux-musleabihf`)
https://github.com/Myriad-Dreamin/tinymist/blob/c830048b6181973117eba4b6ce17af2da4957b73/crates/tinymist-query/src/ty/def.rs#L1193-L1197

```
failures:
---- ty::def::tests::test_ty_size stdout ----
thread 'ty::def::tests::test_ty_size' panicked at crates/tinymist-query/src/ty/def.rs:1194:9:
assertion failed: size_of::<Ty>() == 16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    ty::def::tests::test_ty_size
test result: FAILED. 49 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.74s
error: test failed, to rerun pass `-p tinymist-query --lib`
```

**Package/Software version:**

tinymist extension version: `v0.12.0`.

**Comment by Myriad-Dreamin** [comment]
The correct assertion must be `assert!(size_of::<Ty>() <= size_of::<usize>() * 2);`, to ensure that we won't change size of `Ty` when adding or removing types to the `Ty` enum.
