### ISSUE TITLE
Better expression and type printer

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Myriad-Dreamin/tinymist#765]
When hovering code, expressions and types are printed to show information, such as sampled value of some expression or signature of some function. The current type and expression printer are not perfect in some cases.

- [ ] Improve [`Expr::repr`](https://github.com/Myriad-Dreamin/tinymist/blob/c830048b6181973117eba4b6ce17af2da4957b73/crates/tinymist-query/src/syntax/def.rs#L75).
- [ ] Improve [`Ty::repr`](https://github.com/Myriad-Dreamin/tinymist/blob/c830048b6181973117eba4b6ce17af2da4957b73/crates/tinymist-query/src/ty/describe.rs#L16).
- [ ] Improve [parameter docs's formatter](https://github.com/Myriad-Dreamin/tinymist/blob/c830048b6181973117eba4b6ce17af2da4957b73/crates/tinymist-query/src/docs/def.rs#L87)
- [ ] Improve hover [highlighting](https://github.com/Myriad-Dreamin/tinymist/blob/main/syntaxes/textmate/main.mts).

**Examples**

An example of bad expression formatting of the default value of the `scope` parameter:

```typ
#let touying-equation(
  body: bytes | content | decimal | float | function | int | label | str | type | version,
  block: bool = true,
  numbering: none | str = none,
  scope: dict | dictionary = (:
  ),
  supplement: auto | str = auto,
) = any;
```

Comment: We must print expressions with having print width (80 or 120).

**Examples**

An example of bad parameter docs:

````md
```typ
let text(
  body: content,
  text: str,
  alternates: bool = false,
  baseline: length = 0pt,
  bottom-edge: length | str = "baseline",
  cjk-latin-spacing: auto | none = auto,
  costs: dictionary = (
    hyphenation: 100%,
    runt: 100%,
    widow: 100%,
    orphan: 100%,
  ),
  dir: dir = auto,
  discretionary-ligatures: bool = false,
  fallback: bool = true,
  features: array | dictionary = (:),
  fill: color = luma(0%),
  font: array | text.font = "libertinus serif",
  fractions: bool = false,
  historical-ligatures: bool = false,
  hyphenate: auto | bool = auto,
  kerning: bool = true,
  lang: text.lang = "en",
  ligatures: bool = true,
  number-type: auto | str = auto,
  number-width: auto | str = auto,
  overhang: bool = true,
  region: text.region = none,
  script: auto | str = auto,
  size: text.size = 11pt,
  slashed-zero: bool = false,
  spacing: relative = 100% + 0pt,
  stretch: ratio = 100%,
  stroke: stroke = none,
  style: str = "normal",
  stylistic-set: array | int | none = (),
  top-edge: length | str = "cap-height",
  tracking: length = 0pt,
  weight: int | str = "regular",
);
```

Customizes the look and layout of text in a variety of ways.

This function is used frequently, both with set rules and directly. While the set rule is often the simpler choice, calling the text function directly can be useful when passing text as an argument to another function.

## Example
#set text(18pt)
With a set rule.

#emph(text(blue)[
  With a function call.
])
Parameters
@positional body — Content in which all text is styled according to the other arguments.

@positional text — The text.

@named alternates — Whether to apply stylistic alternates.

Sometimes fonts contain alternative glyphs for the same codepoint. Setting this to true switches to these by enabling the OpenType salt font feature.

#set text(
  font: "IBM Plex Sans",
  size: 20pt,
)

0, a, g, ß

#set text(alternates: true)
0, a, g, ß
@named baseline — An amount to shift the text baseline by.

... (more content of docs is cut here)
````

Comment: the `@positional/@named` annotation style was borrowed from typescript's hover docs, but it is not quite perfect to show very long docs. Besides, more information such as enumerated candidate values of some parameters are not shown in docs, e.g. [`text.bottom-edge`](https://typst.app/docs/reference/text/text/#parameters-bottom-edge) can be `baseline`, `descender`, or `bounds`.

**Examples**

An example of bad type formatting of type of the `numbering` parameter:

```typ
#let touying-mitex(
  mitex: function,
  body: bytes | content | decimal | float | function | int | label | str | type | version,
  block: bool = true,
  numbering: none | str = none,
  supplement: auto | str = auto,
);
```

Comment: A small improvement is that `none` should be placed after `str`.

**Examples**

An example of bad syntax highlighting:

![image](https://github.com/user-attachments/assets/446afa2c-7a07-40a2-b906-23256a8b2350)

Comment: The `type` identifier is not highlighted correctly.

**Comment by Enter-tainer** [comment]
Issues related to column width can be solved by using a pretty printer like https://docs.rs/tiny_pretty/latest/tiny_pretty/. It is very close to what typstyle does.

**Comment by Myriad-Dreamin** [comment]
We will encode expr and type back to typst code so we can use typstyle for pretty printing instead of costing much to improve current impretty printer.
