### ISSUE TITLE
preview tab causes typing lag in VSCODE

### ISSUE THREAD

**Issue by HarryLuoo** [Myriad-Dreamin/tinymist#767]
Typing in VScode has noticeable lagging with preview tab opened. 

vscode version: 1.95.1
tinymist version: 0.12.0

**Additional context**
Typing lag is gone whenever I close the preview tab. No lag when I try to view my changes in .typ via PDF viewer, but they don't render as fast as typst preview, so I would want to use without significant lag if possible.

**Comment by Enter-tainer** [comment]
#757

**Comment by Enter-tainer** [comment]
Sorry, it should be #707
