### ISSUE TITLE
command 'tinymist.onEnter' not found

### ISSUE THREAD

**Issue by 1433223anpeng** [Myriad-Dreamin/tinymist#769]
while  use enter key appearce this bug ,yet can't line feed

**Comment by jchan-legendpower** [comment]
Getting the same issue, I think this is related to the extension shipping with binaries that can't be run on NixOS

**Comment by Myriad-Dreamin** [comment]
This should happen when the language server is not running in backend.

**Comment by Myriad-Dreamin** [comment]
Or specific to NixOS, they replaced the binary in the extension bundle, causing an outdated binary running in backend. To my knowledge, the tinymist binary on nix stable is on some ancient version.

**Comment by bikeshedder** [comment]
I just ran into the very same problem with tinymist running in a Dev Container with Debian 11.

Outside of the Dev Container the extension works as expected.

FYI I also have typst 0.13.1 installed as `~/.local/bin/typst` binary inside my container:

```dockerfile
ARG TYPST_VERSION=0.13.1
RUN curl -L -o /tmp/typst.tar.xz https://github.com/typst/typst/releases/download/v${TYPST_VERSION}/typst-x86_64-unknown-linux-musl.tar.xz \
    && tar -C /tmp -xf /tmp/typst.tar.xz \
    && install -m 755 /tmp/typst-x86_64-unknown-linux-musl/typst ${HOME}/.local/bin/typst \
    && rm -R /tmp/typst*
```

@Myriad-Dreamin Should I open a new issue for that or do you wan to reopen this one?

**Comment by Myriad-Dreamin** [comment]
> I just ran into the very same problem with tinymist running in a Dev Container with Debian 11.
> 
> Outside of the Dev Container the extension works as expected.
> 
> FYI I also have typst 0.13.1 installed as `~/.local/bin/typst` binary inside my container:
> 
> ARG TYPST_VERSION=0.13.1
> RUN curl -L -o /tmp/typst.tar.xz https://github.com/typst/typst/releases/download/v${TYPST_VERSION}/typst-x86_64-unknown-linux-musl.tar.xz \
>     && tar -C /tmp -xf /tmp/typst.tar.xz \
>     && install -m 755 /tmp/typst-x86_64-unknown-linux-musl/typst ${HOME}/.local/bin/typst \
>     && rm -R /tmp/typst*
> [@Myriad-Dreamin](https://github.com/Myriad-Dreamin) Should I open a new issue for that or do you wan to reopen this one?

The `tinymist-x86_64-unknown-linux-gnu` dynamically links to some high version glibc so may not run in debian 11. You could either install `tinymist-x86_64-unknown-linux-musl` to avoid libc issue or upgrade to debian 12 (perhaps containing newer glibc).
