### ISSUE TITLE
Debug message for `sys.inputs.somekey`

### ISSUE THREAD

**Issue by woerndl** [Myriad-Dreamin/tinymist#779]
I'm keeping this brief as I'm not sure if this is a Tinymist or upstream issue of Typst itself.

If you do for example:

``` typ
#let current-time = int(sys.inputs.time)
#let some-variable = int(sys.inputs.key)
```

You get an inline error indicator: dictionary does not contain key […]

The code works, though, and the Typst compiler itself doesn't complain. That's why I assumed this might be an issue on the Tinymist end.

**Comment by Enter-tainer** [comment]
>  and the Typst compiler itself doesn't complain.

i suppose this is because when compile the document using typst-cli, some extra sys.input is provided?

**Comment by woerndl** [comment]
> i suppose this is because when compile the document using typst-cli, some extra sys.input is provided?

Yes, I forgot to mention that. I didn't find a way to provide the sys.inputs, but I just now found the notes on [document preview in the docs](https://myriad-dreamin.github.io/tinymist/feature/preview.html#label-sys.inputs). I assume that should be it.

**Comment by Enter-tainer** [comment]
https://myriad-dreamin.github.io/tinymist/frontend/vscode.html#label-passing-extra-cli-arguments

i guess you are looking for this

**Comment by woerndl** [comment]
Yes, I'm trying to pass the time to the document to switch between dark/light mode, so I'd need to update `tinymist.typstExtraArgs`? But I see `--creation-timestamp` is default?

**Comment by Enter-tainer** [comment]
--creation-timestamp is a different thing. it is used for reproducible compilation.

**Comment by woerndl** [comment]
I see, so editing/updating the `tinymist.typstExtraArgs` on the fly would be the only way? I should add that I mostly view the file outside of VS Code/Tinymist, so the provided dark mode feature unfortunately doesn't help me much.

**Comment by Enter-tainer** [comment]
i think so. currently it's not possible to set sys.input programatically.

**Comment by woerndl** [comment]
Thank you for your help. This leaves the scope of this issue a bit, but is there a documented possibility to use Tinymist as the preview generator outside of supported environments? In my case, Obsidian for example. So basically to open the web preview in Obsidian?

**Comment by Eric-Song-Nop** [comment]
I am not sure how you are editting typst in Obsidian, but there is extension to call tinymist preview as a shell command.

**Comment by woerndl** [comment]
Aaah, a standalone version—something like that was what I was looking for. Thanks! `typst watch` currently works quite well, but partial rendering could be even smoother in terms of preview experience.

About the editing: With [cmarker](https://typst.app/universe/package/cmarker/). Experience is very good so far, but currently you have to take care of the preview yourself.

**Comment by woerndl** [comment]
May I ask if I'm getting the documentation right. I set `tinymist.typstExtraArgs` to `["--input=awa=1", "--input=abaaba=2", "main.typ"]` for testing purposes. And tried to access it with `#repr(sys.inputs.awa)`, but I still get the error message.

<img width="556" alt="test" src="https://github.com/user-attachments/assets/d8bf362a-8f44-4906-9939-fe0a24325886">
<img width="465" alt="test-error" src="https://github.com/user-attachments/assets/8d967356-579c-4565-9a09-a648f284a1f1">

Did I misinterpret the documentation?

**Comment by Kinrany** [comment]
So the issue is that `sys.inputs` is treated by the typst compiler as a static value, and it would require a compiler change to allow looking up arbitrary keys?
