### ISSUE TITLE
Scroll code window to location of preview window

### ISSUE THREAD

**Issue by gamagan** [Myriad-Dreamin/tinymist#780]
Does Tinymist have the ability to scroll the code window to match the location of a click in the preview window? If so, how can I enable that?

**Comment by Enter-tainer** [comment]
currently we do this in a best-effort way. it should work out of the box for basic cases.

**Comment by Myriad-Dreamin** [comment]
The feature is not enabled by default, since it is not perfect:

https://github.com/Myriad-Dreamin/tinymist/blob/bbee391995a657d95585ec1bb7a070d48afc576a/editors/vscode/package.json#L493-L500

**Comment by gamagan** [comment]
Just to be clear. Clicking on the code window does scroll the preview window correctly. My issue is the other way around: clicking the preview window to scroll the code window. That latter behavior is not working for me at all.

**Comment by Eric-Song-Nop** [comment]
Click preview should bring you to the position in editor, you must encountered some bug or wrong configuration, may I have your environment or log.

**Comment by gamagan** [comment]
> Click preview should bring you to the position in editor, you must encountered some bug or wrong configuration, may I have your environment or log.

I can, but I've never done it. What steps should I do to provide you with the info?

**Comment by Myriad-Dreamin** [comment]
Will be fixed in v0.12.2
