### ISSUE TITLE
Add option that some functions autocompletion adds `[]` instead of `()`

### ISSUE THREAD

**Issue by Sinthoras7** [Myriad-Dreamin/tinymist#789]
**Motivation**

Some functions only have an argument of type content as the only mandatory argument. When I do not want to set any of the optional arguments e.g. `#footnote[My text $x^2$]` is a nicer syntax than `#footnote([My text $x^2$])`, so I remove the parenthesis and add the square brackets. For some functions (e.g. footnote) it is very common. So it would be nice if there is an option for the user to give a list of functions for which by default the autocompletion should add the `[]` instead of the `()`.

**Description**

Add the option that the user can give a list of functions for which by default the autocompletion should add `[]` instead of `()`.

**Examples/Questions**

This is useful for a variety of commonly used functions, e.g. footnote, smallcaps, strong, ...

**Comment by Eric-Song-Nop** [comment]
Passing too many options to language server might not be ideal, especially considering function with same name.

A better solution might be annotating such information in doc comment for functions, while there is no real doc comment spec for Typst yet.
