### ISSUE TITLE
Support prettypst

### ISSUE THREAD

**Issue by George-Miao** [Myriad-Dreamin/tinymist#794]
**Motivation**

[prettypst](https://github.com/antonWetzel/prettypst) is another formatter for typst written in Rust. Currently it does not have vscode plugin and requires `custom-local-formatters` to work with vscode/vscodium. It would be great if tinymist can integrate it.

**Description**

Add fourth option to `formatterMode`, namely `prettypst`. When user selects it, run [`format_str`](https://github.com/antonWetzel/prettypst/blob/a724b56de0527faf0f1f1eecb17d0b847872411c/src/lib.rs#L120) whenever a format task is spawned. 

**Questions**

I'm willing to author a PR if needed.

**Comment by Eric-Song-Nop** [comment]
It seems that prettypst is not distributed as a library on crates.io yet, thus I assume it is not so easy to be used in Tinymist.

Btw, I personally hope to drop the support for typstfmt as it has been achieved for some days.

**Comment by Myriad-Dreamin** [comment]
prettypst is not an actively maintained formatter so we may not add it. Instead you might use it independently by some LSP wrapper like null-ls in neovim.

For typstfmt, I had plan to remove it but some people discouraged it since they preferred typstfmt than typstyle.
