### ISSUE TITLE
Characters do not match in a pattern

### ISSUE THREAD

**Issue by Frozoleo** [Myriad-Dreamin/tinymist#839]
**Describe the bug**
when used in a pattern, the characters displayed do not match those requested.
![Capture](https://github.com/user-attachments/assets/2de646ca-4fd4-4bdb-b19c-bec3471d5c26)

**Package/Software version:**

VSCode version(Help -> About):
Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045

tinymist extension version: `v0.12.2`

**Logs:**

tinymist server log(Output Panel -> tinymist):
```plain

```

tinymist client log(Help -> Toggle Developer Tools -> Console):
```plain

```

**Additional context**

**Comment by Myriad-Dreamin** [comment]
Could you attach the file content to test in the screenshot?

**Comment by Frozoleo** [comment]
the initial file is heavy and uses a template in addition.
I reproduced the bug with a second file containing the following code.

`#sys.version

#outline()

  $checkmark$
  #emoji.crossmark
  #text(1.3em,$bold(circle.stroked)$)

   #box(
    width : 1em,
    height : 1em,
    [
      #emoji.pen.fountain
      #place(dy : -0.9em,dx : 0.3em,rotate(-45deg,text(1.5em)[*?*]))
      
    ]
  )
  
  #emoji.magnify.r
  #box(
    baseline: 20%,
    [
      #text(1.3em)[#emoji.bell]
      #place(center+horizon,[R])
    ]
  )

  #emoji.gem
  

  #emoji.star.glow
  #emoji.star


  #text(font : "Android Emoji",emoji.bubbles)
  #text(font : "Noto emoji",emoji.bubbles)
  #text(emoji.bubbles)

  #polygon(
    (0pt, 0pt),
    (1em, 0pt),
    (1.2em, 0.1em),
    (1em, 0.2em),
    (0pt, 0.2em),
  )
  

  $A = diameter$
  $A = emptyset$
  $A = nothing$

  #line(length : 20%)
  #line(length : -20%)

#let taille = 0.7 * 20pt

  #let pat_a = pattern(
    size : (taille,1.5*taille),
    relative: "self",
    place(text(1.4em,box($checkmark$)))
  )
  #let pat_b = pattern(
    size : (taille,1.5*taille),
    box(inset : (top : 0.1em),emoji.star)
  )
  #let pat_c = pattern(
    size : (1.5*taille,1.5*taille),
    box(inset : (top : 0.2em),text(0.9em,emoji.circle.stroked))
  )
  #let pat_d = pattern(
    [*!*]
  )

  #block(height : 100pt,width : 100pt,fill : pat_a)
  #block(height : 100pt,width : 100pt,fill : pat_b)
  #block(height : 100pt,width : 100pt,fill : pat_c)
  #block(height : 100pt,width : 100pt,fill : pat_d)`

**Comment by Eric-Song-Nop** [comment]
I am sure it is a bug from upstream Typst. Might be related to: https://github.com/typst/typst/issues/5428, maybe you can report it there also.
Although Tinymist's preview is also affected, but it seems to perform better than Typst compiler in this case, and I suggest we wait until it is fixed bt the upstream first

**Comment by Frozoleo** [comment]
Thanks for your answer! Indeed, issue 5428 seems to deal with the same underlying problem. For the moment I replaced the emoji with other symbols that lead back to the same idea. I hesitated to post directly on the typst github but since this bug does not seem to occur on the online editor, I thought it must be related to tinymist...
