### ISSUE TITLE
abnormal auto completion got from VS Code tinymist extension

### ISSUE THREAD

**Issue by mmonci** [Myriad-Dreamin/tinymist#852]
**Describe the bug**
the hint of image file path always contain **an unexpected ”../“**. Got it every time I call image function.

An example shown below.

![show](https://github.com/user-attachments/assets/e2573211-20b1-4e12-ad68-cf4346af6aa0)

**Package/Software version:**

tinymist extension version: `v0.12.2`. I just downloaded the extension in VS Code.

**Comment by Eric-Song-Nop** [comment]
I can confirm that it is also happening on Neovim, so it's a bug on the server side.

I am looking into this bug
