### ISSUE TITLE
Precompiled version delivered with VSCode extension not compatible with RHEL 8

### ISSUE THREAD

**Issue by bendem** [Myriad-Dreamin/tinymist#878]
**Describe the bug**

Installing the extension in vscode on RHEL 8 causes the following error and breaks the editing of .typ files:

> Failed to activate tinymist: Error: Could not find a valid tinymist binary. Bundled ('/home/demarteaub/.vscode-server/extensions/myriad-dreamin.tinymist-0.12.2/out/tinymist'): failed to probe: return status: 1 In PATH ('tinymist'): failed to probe: error: spawnSync tinymist ENOENT

If I try to start the process manually, I get the following error:

```shell
>  ~/.vscode-server/extensions/myriad-dreamin.tinymist-0.12.2/out/tinymist
~/.vscode-server/extensions/myriad-dreamin.tinymist-0.12.2/out/tinymist: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/demarteaub/.vscode-server/extensions/myriad-dreamin.tinymist-0.12.2/out/tinymist)
~/.vscode-server/extensions/myriad-dreamin.tinymist-0.12.2/out/tinymist: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by /home/demarteaub/.vscode-server/extensions/myriad-dreamin.tinymist-0.12.2/out/tinymist)
```

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045
```

tinymist extension version: `v0.11.0`. Get it by `tinymist --version` in terminal.
```plain
> tinymist --version
zsh: command not found: tinymist
```

**Logs:**

tinymist server log(Output Panel -> tinymist):
```plain
N/A
```

tinymist client log(Help -> Toggle Developer Tools -> Console):
```plain
N/A
```

**Additional context**
I just installed the extension from vs code, the error message just tells me there was a problem with tinymist, after that, I can't edit any .typ file: hitting enter causes `command 'tinymist.onEnter' not found`.

I can install tinymist separately, but it would be good if the extension told me that (and how) and didn't break the editor.

**Comment by Enter-tainer** [comment]
we build our binary on ubuntu 22.04 or 20.04(i cannot remember exactly). The default glibc version is a little bit modern for rhel.

At this moment, you can try build the binary yourself for platforms we didnt ship useable binaries.

**Comment by Enter-tainer** [comment]
command 'tinymist.onEnter' not found.

this should be another problem. i remember i've seen this in other issues before.

**Comment by Myriad-Dreamin** [comment]
> command 'tinymist.onEnter' not found.

This is just because the tinymist server is not running in backend. No lsp command, including the `tinymist.onEnter`, is registered to editor. Since it is not running, we don't expect the extension to work at all.

**Comment by Myriad-Dreamin** [comment]
We won't maintain extensions for all distro, so the package registry of RHEL 8 should build and add tinymist package for RHEL 8 users.

![image](https://github.com/user-attachments/assets/f2a3b079-f567-4b85-b1d2-0631f4c7469f)

Some other thought: we may reach wider support by changing the libc from glibc to musl, but this will introduce some challenges.

**Comment by bendem** [comment]
This issue isn't about supporting RHEL8, it's about telling the user what's wrong so they can fix it. The error message could be improved and the extension shouldn't break editing if the lsp is not running.
