### ISSUE TITLE
Syntax highlighting issue with single $ in raw inline or block code

### ISSUE THREAD

**Issue by produnis** [Myriad-Dreamin/tinymist#886]
Hi there,

I’m using TinyMist Typst 0.12.2 with VSCodium on Arch Linux.

I’ve encountered an issue where writing a single `$` inside raw inline or block code causes the syntax highlighting to break.

Writing a single `$` in inline code like this:

```
you can use a #strong[single `$`] to address columns
``` 
This breaks the syntax highlighting for the rest of the document.

The same issue occurs in block code with triple backticks.

Adding another line containing a single `$` elsewhere in the document seems to resolve the issue and restore syntax highlighting.

**Expected Behavior**
The syntax highlighting should handle single `$` characters in inline and block raw code without breaking.

**Actual Behavior**
Syntax highlighting gets confused when a single `$` is used in raw inline or block code until another $ appears elsewhere in the document.

Let me know if you need additional information or logs to debug this. Thank you!

**Comment by Myriad-Dreamin** [comment]
Could you give a screenshot and tell which theme did you use? I cannot reproduce bad syntax highlighting in my end.

![image](https://github.com/user-attachments/assets/c2282099-d08d-451a-a500-393e1328b690)

**Comment by produnis** [comment]
Hi there, 
the problem comes up if you wrap code inside a function.

![](https://i.imgur.com/sMCOr3u.jpeg)

Find this minimal example at https://github.com/produnis/minimal_examples/tree/typsthighlight

I am using theme "`Default Light Modern`".

**Comment by Myriad-Dreamin** [comment]
Hi, I unluckily still cannot reproduce it on my computer.

![image](https://github.com/user-attachments/assets/b14985ae-cbfa-459b-bbef-3fd3dce56800)

However, I have a new finding. I noticed the content of the first raw block in your screenshot is highlighted, but this doesn't in my screenshot. I suspect some other extensions are hijacking and confusing the syntax highlighting. Could you turn off all extension, only keep R and tinymist extension activated, and then test it again?

Btw, I'm using the R's syntax highlighting from this extension (id: `REditorSupport.r`) without adding any configuration about this extension:

![image](https://github.com/user-attachments/assets/f9b21715-376a-4928-b3f6-e2f0b1698bac)

**Comment by produnis** [comment]
thx for your time and efforts. I disabled all extensions, and after restart, the problem is gone.
Now I have to figure out what extension broke it.
THX AGAIN!!!

**Comment by produnis** [comment]
got it, it is the official quarto-extension `quarto-vscode`, that will cause my problems. tzü...
