### ISSUE TITLE
Syntax highlighting issues with terms

### ISSUE THREAD

**Issue by eduardz1** [Myriad-Dreamin/tinymist#889]
**Describe the bug**

Terms that contain a colon as raw text break syntax highlighting for the whole document after that. For example

```typ
/ term `:`: description
```

appears as

![screenshot-2024-11-22-17-17-04](https://github.com/user-attachments/assets/38f312ac-b654-436b-b511-e393b365fec6)

Notice description being highlighted as raw code, after that syntax highlighting is completely broken in the rest of the document

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.9.3-76060903-generic
```

tinymist extension version: `v0.11.0`. Get it by `tinymist --version` in terminal.
```plain
Name: Tinymist Typst
Id: myriad-dreamin.tinymist
Description: An integrated language service for Typst
Version: 0.12.2
Publisher: Myriad Dreamin
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=myriad-dreamin.tinymist
```

**Comment by eduardz1** [comment]
I noticed that the same problem is also present on GitHub's syntax highlighting. Is it perhaps something that should be reported elsewhere?

**Comment by Myriad-Dreamin** [comment]
@eduardz1 Hi, GitHub's syntax highlighter used a different syntax definition merged in [Pull request: Add Typst in linguist](https://github.com/github-linguist/linguist/pull/6379). We are thinking of making a PR to use our syntax definition instead, but we lack of volunteer to make that, follow, and solve related issues.
