### ISSUE TITLE
Crashes & Performance issues while using CeTZ-Plot

### ISSUE THREAD

**Issue by sukulent** [Myriad-Dreamin/tinymist#890]
**Describe the bug**

Hello, I have been using tinymist in VSCode for some time, but finally did the switch to neovim.
I hoped that the problems will go away, but it seems that tinymist is the issue.

When I enter a .typ file, the tinymist starts and it takes good seconds before it responds to any input, which I guess would be expected, considering that typst takes a little less to compile it. I am using the CeTZ-Plot package for plotting graphs, currently working on file with 7 graphs (in sum ~2.3k points) so there's stuff going on, but it still is just a few pages.

My first problem is the performance when editing: i.e. when I type a variable name, it grabs the first letter, says: "unknown variable" for few seconds before it updates, or the variable content popups take a long time, and in that time things like go-to-definition don't work, as the server is processing the previous action. Sometimes it seems like it gets stuck calculating something that I already changed, before it can notice that it changed. It works quickly right now as I am writing this issue, as it has time to go idle, but when editing it often gets behind.

Second problem are the semi-frequent crashes, see the included log.
Also, the highlighting of `#function`  sometimes overflows and highlights a few characters in front of the `#`, but that's not my main point.

If there are any more logs needed or something I could do, I can try. I just want to report the rust panic and point out performance issues when using the plot package.

**Package/Software version:**
```plain
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1727870382
(on Arch Linux)
```

**Logs:**
These are the last 3 lines from `~/.local/state/nvim/lsp.log` after one tinymist crash, with rust panicking in the last
```plain
[ERROR][2024-11-22 11:25:59] .../vim/lsp/rpc.lua:770	"rpc"	"/home/sukulent/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-11-22T10:25:59Z INFO  sync_lsp] handling textDocument/documentHighlight - (319) at Instant { tv_sec: 1967, tv_nsec: 584135220 }\n"
[ERROR][2024-11-22 11:25:59] .../vim/lsp/rpc.lua:770	"rpc"	"/home/sukulent/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-11-22T10:25:59Z INFO  sync_lsp] handled  textDocument/documentHighlight - (319) in 95.78µs\n"
[ERROR][2024-11-22 11:25:59] .../vim/lsp/rpc.lua:770	"rpc"	"/home/sukulent/.local/share/nvim/mason/bin/tinymist"	"stderr"	"[2024-11-22T10:25:59Z INFO  sync_lsp] notifying textDocument/didChange - at Instant { tv_sec: 1967, tv_nsec: 846758483 }\nthread 'main' panicked at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/mod.rs:2207:36:\nslice index starts at 21186 but ends at 21139\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

**Comment by Myriad-Dreamin** [comment]
Hello, thank you for submitting the issue. There are two points to solve before we discuss them:
- you seems to be putting multiple issues in a single issue, making it difficult to solve them one by one.
- Neither source code triggering the issues nor the steps to reproduce. You also didn't provide the settings and configuration about tinymist. So we only know there are issues encountered on your side but we cannot step in and investigate them on our side.

You could check the closed issues about [neovim](https://github.com/Myriad-Dreamin/tinymist/issues?q=is%3Aissue+is%3Aclosed+neovim) to learn how to solve above points.

Short note: Specific to slow completion with using large packages like cetz, we have improved the cache efficiency on analyzing source code in packages in 0.12.4, you could upgrade and check them again.
