### ISSUE TITLE
Enhance multiple page view

### ISSUE THREAD

**Issue by jbae-89** [Myriad-Dreamin/tinymist#898]
**Motivation**
By default pages can only be previewed in one column which becomes cumbersome on short documents where you'd like to see changes on multiple pages at the same time
![1](https://github.com/user-attachments/assets/c9f773a0-ff31-4dd0-abcc-35403da4ffce)

**Description**

Allow users to display document pages side-by-side or in multiple columns
![2](https://github.com/user-attachments/assets/fae805d9-70d7-4cf7-88c8-3ad608852b87)
Example of a 2x2 view layout

**Examples**
A small button here could allow users to change how pages are shown in preview (example button drawn in red)
![3](https://github.com/user-attachments/assets/883a6aed-5289-4066-9418-22e70d7a8eec)

**Comment by Eric-Song-Nop** [comment]
Duplicate of #629

**Comment by jbae-89** [comment]
@Eric-Song-Nop, apologies, I didn't see that. Closing
