### ISSUE TITLE
Compilation to SVG in command line

### ISSUE THREAD

**Issue by pammacdotnet** [Myriad-Dreamin/tinymist#906]
I remember it was possible to generate a SVG image from a .typ file with the command `typst-preview` but this is no longer possible. Could this feature be restored?

**Comment by Enter-tainer** [comment]
btw, you can use typst-cli to do this

**Comment by Myriad-Dreamin** [comment]
I don't know but I don't believe we even provide such feature in `typst-preview` in past. Could you describe how did you use the feature in `typst-preview` to help us recall the exact deleted feature?
