### ISSUE TITLE
Error while trying to read the output logs of tinymist on vscode

### ISSUE THREAD

**Issue by Illicitline45** [Myriad-Dreamin/tinymist#950]
**Describe the bug**
When trying to read the output of tinymist, it raises ```Cannot read properties of undefined (reading 'client')```

**Package/Software version:**
tinymist vscode extension version: `v0.12.8`.

**Comment by Myriad-Dreamin** [comment]
Before next release (tomorrow), you can manually switch to the output channel in the output tab.
