### ISSUE TITLE
Integrated `typstyle` escape hatch not respected

### ISSUE THREAD

**Issue by ntjess** [Myriad-Dreamin/tinymist#996]
According to the [docs](https://github.com/Enter-tainer/typstyle?tab=readme-ov-file#escape-hatch):
> If you find typstyle is not working as expected, you can use // @typstyle off or /* @typstyle off */ to disable the formatter on the next node of code.

However, neither comment style prevents `tinymist` from applying formatting in certain circumstances.

In VSCode:
```typst
#if true {
  // @typstyle off
  let x = (
  "A message that will be split into multiple lines to ensure that each"
  + " line does not exceed sixty characters in length. This is a common"
  + " practice to improve readability and maintainability of the code."
  )
  // @typstyle on
}

```

Without the `if` block, the escape hatch works. Inside `if`, it fails.

_Side note: I think splitting operators to their own lines is a "favorable" default behavior compared to merging them into one line when the result would be very long_

**Comment by Enter-tainer** [comment]
hi, i believe this is a typstyle bug. could you please also open an issue in typstyle's repo?
